#import "../templates/preamble.typ": *


#problem-block(number: 1, title: [Sum of multiples of 5 or 7], level: 1)[
If we list all the natural numbers less than $20$ that are multiples of $5$ or $7$, we get $5$, $7$, $10$, $14$ and $15$. The sum of these numbers is $51$.

*Find the sum of all multiples of $5$ or $7$ less than $2013$.*

_(Inspired by problem 1 of Project Euler)_
]


#problem-block(number: 2, title: [Sum of odd-valued terms in Fibonacci sequence], level: 1)[
Each new term in the Fibonacci sequence is generated by adding the two preceding terms. Starting with $1$ and $1$, the first $10$ terms are as follows:
$ 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, dots $

*By considering the terms in the Fibonacci sequence whose values do not exceed $4$ million, find the sum of the odd-valued terms.*

_(Inspired by problem 2 of Project Euler)_
]


#problem-block(number: 3, title: [Largest prime factor of composite number], level: 1)[
The prime factors of the number $2013$ are $3$, $11$ and $61$, because $3 times 11 times 61 = 2013$.

*What is the largest prime factor of the number $20130101$?*

_(Inspired by problem 3 of Project Euler)_
]


#problem-block(number: 4, title: [Largest palindrome of multiplying two numbers], level: 2)[
A palindromic number reads the same from left to right and from right to left.\
The largest palindrome that can be obtained by multiplying two 2-digit numbers is $9009 = 99 times 91$.

*What is the largest palindrome that can be obtained by multiplying a 4-digit number by a 3-digit number?*

_(Inspired by problem 4 of Project Euler)_
]


#problem-block(number: 5, title: [Sum of digits of $2^2222$], bm-title: [Sum of digits of 2^2222], level: 1)[
$2^15 = 32768$ and the sum of its digits is $3 + 2 + 7 + 6 + 8 = 26$.

*What is the sum of the digits that make up the number $2^2222$?*

_(Inspired by problem 16 of Project Euler)_
]


#problem-block(number: 6, title: [Sum of digits in number $2013!$], bm-title: [Sum of digits in number 2013!], level: 1)[
$n!$ means $n times (n-1) times dots.c times 3 times 2 times 1$.\
For example, $10! = 10 times 9 times dots.c times 3 times 2 times 1 = 3628800$.\
The sum of the digits in the number $10!$ is $3 + 6 + 2 + 8 + 8 + 0 + 0 = 27$.

*Find the sum of the digits in the number $2013!$.*

_(Inspired by problem 20 of Project Euler)_
]


#problem-block(number: 7, title: [What is the $23456$#super[th] prime number?], bm-title: [What is the 23456th prime number?], level: 2)[
By listing the first six prime numbers: $2$, $3$, $5$, $7$, $11$ and $13$, we see that the $6$#super[th] prime number is $13$.

*What is the $23456$#super[th] prime number?*

_(Inspired by problem 7 of Project Euler)_
]


#problem-block(number: 8, title: [Rectangle-$6400$], bm-title: [Rectangle-6400], level: 3)[
In a rectangle with a length of $4$ and a width of $3$, we can draw $12$ squares with a side length of $1$, $6$ squares with a side length of $2$, and $2$ squares with a side length of $3$. In total, we can draw $20$ squares. We will call this a rectangle-$20$.

*What is the area of ​​the rectangle-$6400$ whose shape is closest to a square?*

Note: The dimensions are whole numbers for both the rectangle and the squares.

_(Inspired by the 2012 CMP problem from the mathematics and physics circle of the Société jurassienne d'émulation)_
]


#problem-block(number: 9, title: [Pythagorean triplet], level: 2)[
A triplet of non-zero natural numbers $(a, b, c)$ is Pythagorean if $a^2 + b^2 = c^2$. For example, $(3, 4, 5)$ is a Pythagorean triplet.

*Among the Pythagorean triples $(a, b, c)$ such that $a + b + c = 3600$, give the largest product $a times b times c$.*

_(Inspired by problem 9 of Project Euler)_
]


#problem-block(number: 10, title: [Sum of prime numbers], level: 2)[
The sum of the prime numbers between $1$ and $10$ is $2 + 3 + 5 + 7 = 17$.

*Find the sum of the prime numbers between $1$ and $10 thin 000 thin 000$.*

_(Inspired by problem 10 of Project Euler)_
]


#problem-block(number: 11, title: [Mirror of number], level: 1)[
The "mirror image of a number $n$" is the number $n$ written from right to left. For example, $op("mirror")(7423) = 3247$.

*What is the largest number less than $10$ million that has the property: $op("mirror")(n) = 4 times n$?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 12, title: [Triangular numbers with many divisors], level: 3)[
The sequence of triangular numbers is generated by adding the natural numbers. Thus, the $7$#super[th] triangular number is $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten triangular numbers are as follows:
$ 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, dots $

Let us list the divisors of the first seven triangular numbers:

$1 : 1$\
$3 : 1, 3$\
$6 : 1, 2, 3, 6$\
$10 : 1, 2, 5, 10$\
$15 : 1, 3, 5, 15$\
$21 : 1, 3, 7, 21$\
$28 : 1, 2, 4, 7, 14, 28$

We can see that $28$ is the first triangular number with more than five divisors.

*What is the value of the first triangular number with more than one thousand divisors?*

_(Inspired by problem 12 of Project Euler)_
]


#problem-block(number: 13, title: [Palindrome square], level: 1)[
The smallest palindromic square with an even number of digits is $698896 = 836^2$.

*What is the next palindromic square?*

_(Source: The Mathematical Gazette)_
]


#problem-block(number: 14, title: [Longest Syracuse sequence], level: 1)[
In mathematics, a "Syracuse sequence" is a sequence of natural numbers defined as follows:

We start with an integer greater than zero; if it is even, we divide it by $2$; if it is odd, we multiply it by $3$ and add $1$.\
By repeating the operation, we obtain a sequence of positive integers, each of which depends only on its predecessor.

There is a conjecture that says that the Syracuse sequence of any strictly positive integer reaches $1$.

For example, starting from 14, we construct the sequence of numbers: $14$, $7$, $22$, $11$, $34$, $17$, $52$, $26$, $13$, $40$, $20$, $10$, $5$, $16$, $8$, $4$, $2$, $1$. This is called the Syracuse sequence of the number $14$. Here, it has a length of $18$.

*For what starting number less than $1 thin 500 thin 000$ do we obtain the longest Syracuse sequence?* There are two solutions, give the smallest one.

_(Inspired by problem 14 of Project Euler)_
]


#problem-block(number: 15, title: [Numbers of Mage Hic], level: 3)[
Fill in a $3 times 3$ grid with all the numbers from $1$ to $9$ (green squares). Then calculate the products of the three numbers in each row and each column (grey squares). Finally, add these six products together to obtain the blue number ($450$ in the example given).

#align(center)[
  #v(1em)
  #image(width: 100pt, "../figures/015.png")
  #v(1em)
]

*Of the $362 thin 880$ possible grids, what is the minimum blue number and the maximum blue number? Give the product of these two numbers as the result.*

_(Inspired by problem 12 from the 2013 FFJM individual quarter-Final: "Le nombre du Mage Hic")_
]


#problem-block(number: 16, title: [THREE x NINE = TROIS x NEUF], level: 3)[
A cryptarithm is a numerical and logical puzzle consisting of a mathematical equation in which letters represent numbers to be found. Each different letter represents a different number, and each number is represented by the same letter.

*Solve the cryptarithm below* (give the product obtained as the answer):

#align(center)[`THREE x NINE = TROIS x NEUF`]

*Constraints:*\
`THREE` and `NEUF` are multiples of $9$;\
`TROIS` and `NINE` are multiples of $3$.

_(Problem 18 from the quarter-final of the 2003 mathematical and logical games)_
]


#problem-block(number: 17, title: [Amicable numbers], level: 3)[
Let $d(n)$ be the sum of the proper divisors of $n$ (divisors strictly smaller than $n$). If $d(a)=b$ and $d(b)=a$, with a different from $b$, then $a$ and $b$ are said to be amicable.\
For example, the proper divisors of $220$ are $1$, $2$, $4$, $5$, $10$, $11$, $20$, $22$, $44$, $55$ and $110$; therefore $d(220) = 284$. The proper divisors of $284$ are $1$, $2$, $4$, $71$ and $142$; therefore $d(284) = 220$. $220$ and $284$ are two amicable numbers.\
The sum of the amicable numbers between $1$ and $1000$ is $220 + 284 = 504$.

*What is the sum of the amicable numbers between $1$ and $100 thin 000$?*

_(Inspired by problem 21 of Project Euler)_
]


#problem-block(number: 18, title: [Sum of non-abundant numbers], level: 3)[
A perfect number is a number whose sum of proper divisors is exactly equal to the number itself. For example, the sum of the proper divisors of 28 would be $1 + 2 + 4 + 7 + 14 = 28$, which means that $28$ is a perfect number.

A number $n$ is called deficient if the sum of its proper divisors is less than $n$, and it is called abundant if this sum is greater than $n$.

Since $12$ is the smallest abundant number ($1 + 2 + 3 + 4 + 6 = 16$), the smallest number that can be written as the sum of two abundant numbers is $24$.

*Find the sum of all positive integers less than or equal to $2013$ that #underline[cannot] be written as the sum of two abundant numbers.*

_(Inspired by problem 23 of Project Euler)_
]


#problem-block(number: 19, title: [Close encounters of the fourth kind], level: 1)[
Little green men meet little blue men. To their great surprise, they notice that their hands do not have the same number of fingers: $7$ for the blue ones and $8$ for the green ones. But the scientists of both peoples notice that if you count on your fingers as shown in the figure, moving back and forth from the little finger to the thumb, then from the thumb to the little finger, certain numbers can be counted on both the ring finger of the blue hands and the ring finger of the green hands ($2$ and $14$, for example).\
These numbers have been termed "annular" by scholars.

#align(center)[
  #v(1em)
  #image(width: 300pt, "../figures/019.jpg")
  #v(1em)
]

*Calculate the sum of the ring numbers between $1$ and $2013$.*

_(Inspired by a problem from the mathematical and logical games championship)_
]


#problem-block(number: 20, title: [Hercules and the hydra], level: 3)[
A battle between Hercules and one (or more) hydra(s) can be described by the following steps:
- On the first blow, the Hydra loses a head, and a copy of the wounded Hydra (that is, one with one less head) appears. On the second blow, a Hydra loses a head, and two copies of the wounded Hydra appear. On the tenth blow, a Hydra loses a head, so ten copies appear, and so on.
- When a one-headed Hydra is struck, it disappears.
- To complicate matters, the treacherous Hera forces Hercules to cut off the heads in the worst possible order, so that it takes him as long as possible to destroy the Hydras.

#align(center)[
  #v(1em)
  #image(width: 240pt, "../figures/020.gif")
  Example: Hercules fights two two-headed hydras and two one-headed hydras.
  #v(1em)
]

*Assuming Hercules is capable of cutting off a head every second, how many seconds will it take him to defeat a four-headed hydra?*

_(Jean-Bernard Roux's problem)_
]


#problem-block(number: 21, title: [Happy new year 2013!], level: 2)[
$2013$ has an interesting feature: it is the first year since $1987$ to be composed of all different digits. A period of $26$ years separates these two dates.

*Between year $1$ and $2013$ (inclusive):*

*a) How many years have there been with all different digits? (Years $1$ through $9$ will be counted in this number).*\
*b) What was the length (in years) of the longest period between two dates with all different digits?*

*Give the product of the results of a) and b).*

_(Proposed by Le Coyote)_
]


#problem-block(number: 22, title: [Eightfold anagrams], level: 2)[
Mathilde found two surprising six-digit numbers. When multiplied by $8$, they produce a six-digit number written with the same digits in a different order. Even better: these two numbers are also anagrams!

*What are Mathilde's numbers?* Give the sum of the two numbers.

_(Inspired by problem 14 from the quarter-final of the 2010 mathematical and logical games)_
]


#problem-block(number: 23, title: [Paths in a grid], level: 2)[
Starting from the top left corner of a $2 times 2$ grid, there are $6$ paths to the bottom right corner, moving only to the right or down.

#align(center)[
  #v(1em)
  #image(width: 150pt, "../figures/023.gif")
  #v(1em)
]

*How many such paths are there in a $30 times 20$ grid?*

_(Inspired by problem 15 of Project Euler)_
]


#problem-block(number: 24, title: [Lexicographic permutations], level: 2)[
A permutation is an ordered arrangement of objects. For example, $3124$ is a possible permutation of the digits $1$, $2$, $3$ and $4$.\
The list of permutations in lexicographical order of $0$, $1$ and $2$ is as follows:
$ 012, 021, 102, 120, 201, 210 $

*In lexicographical order, what is the two-millionth permutation of the digits $0$, $1$, $2$, $3$, $4$, $5$, $6$, $7$, $8$, $9$?*

_(Inspired by problem 24 of Project Euler)_
]


#problem-block(number: 25, title: [First Fibonacci number with $2013$ digits], bm-title: [First Fibonacci number with 2013 digits], level: 1)[
The Fibonacci sequence is defined by the recurrence relation:
$ F_n = F_(n-1) + F_(n-2), "where" F_1 = 1 "and" F_2 = 1. $

Thus, the first $12$ terms are: $1$, $1$, $2$, $3$, $5$, $8$, $13$, $21$, $34$, $55$, $89$, $144$, ...\
The $12$th term, $F_12$, is the first term that contains $3$ digits.

*What is the index of the first term in the Fibonacci sequence that contains $2013$ digits?*

_(Inspired by problem 25 of Project Euler)_
]


#problem-block(number: 26, title: [Number divisible by pieces], level: 3)[
*Find an integer $c_1 c_2 c_3 dots.c c_9$ composed of all digits from $1$ to $9$, such that $c_1 dots.c c_k$ is divisible by $k$, for $k=1,dots,9$.*

Let's take a $3$-digit example: $321$.

$3$ is divisible by $1$.\
$32$ is divisible by $2$.\
$321$ is divisible by $3$.

_(Source unknown)_
]


#problem-block(number: 27, title: [Euler's polynomial for prime numbers], level: 3)[
Euler published the remarkable quadratic polynomial:
$ n^2 + n + 41 $

It turns out that this formula provides $40$ prime numbers for successive values of $n$ ranging from $0$ to $39$. However, when $n=40$, $40^2+40+41 = 40(40+1)+41$ is divisible by $41$.

Using a computer, the incredible formula $n^2 - 79 n + 1601$ was discovered. It provides $80$ prime numbers for successive values of $n$ ranging from $0$ to $79$ (each prime number appears twice):

$1601$, $1523$, $1447$, $1373$, $1301$, $1231$, $1163$, $1097$, $1033$, $971$, $911$, $853$, $797$, $743$, $691$, $641$, $593$, $547$, $503$, $461$, $421$, $383$, $347$, $313$, $281$, $251$, $223$, $197$, $173$, $151$, $131$, $113$, $97$, $83$, $71$, $61$, $53$, $47$, $43$, $41$, $41$, $43$, $47$, $53$, $61$, $71$, $83$, $97$, $113$, $131$, $151$, $173$, $197$, $223$, $251$, $281$, $313$, $347$, $383$, $421$, $461$, $503$, $547$, $593$, $641$, $691$, $743$, $797$, $853$, $911$, $971$, $1033$, $1097$, $1163$, $1231$, $1301$, $1373$, $1447$, $1523$, $1601$.


The product of the coefficients, $-79$ and $1601$, gives $-126479$.

Consider quadratic polynomials of the form:\
$n^2 + a n + b, "where" |a| < 1500 "and" |b| < 1500$\
where $|n|$ is the absolute value of $n$ (for example, $|11| = 11$ and $|-4| = 4$).

*Give the product of the coefficients $a$ and $b$ of the quadratic polynomial that generates the longest sequence of prime numbers for successive values of n, starting from $n=0$.*

_(Inspired by problem 27 of Project Euler)_
]


#problem-block(number: 28, title: [Spiral numbers], level: 2)[
Starting with the number $1$, and turning clockwise, a $5 times 5$ spiral is constructed as follows:

#show "red21": text(fill: red, weight: "bold")[21]
#show "red25": text(fill: red, weight: "bold")[25]
#show "red7": text(fill: red, weight: "bold")[7]
#show "red9": text(fill: red, weight: "bold")[9]
#show "red1": text(fill: red, weight: "bold")[1]
#show "red5": text(fill: red, weight: "bold")[5]
#show "red3": text(fill: red, weight: "bold")[3]
#show "red17": text(fill: red, weight: "bold")[17]
#show "red13": text(fill: red, weight: "bold")[13]

#align(center)[
```
red21 22 23 24 red25
20  red7  8  red9 10
19  6  red1  2 11
18  red5  4  red3 12
red17 16 15 14 red13
```
]

We can verify that the sum of the numbers on the diagonals is $101$.

*What is the sum of the numbers on the diagonals of a $2013 times 2013$ spiral constructed in the same way?*

_(Inspired by problem 28 of Project Euler)_
]


#problem-block(number: 29, title: [Distinct powers], level: 2)[
Consider $a^b$ for $2 <= a <= 5$ and $2 <= b <= 5$:
$
2^2=4, 2^3=8, 2^4=16, 2^5=32\
3^2=9, 3^3=27, 3^4=81, 3^5=243\
4^2=16, 4^3=64, 4^4=256, 4^5=1024\
5^2=25, 5^3=125, 5^4=625, 5^5=3125
$

If we sort these numbers in ascending order, removing any duplicates, we obtain a sequence of $15$ distinct terms:
$ 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125 $

*How many distinct terms are there in the sequence obtained as above for $2 <= a <= 1000$ and $2 <= b <= 1000$?*

_(Inspired by problem 29 of Project Euler)_
]


#problem-block(number: 30, title: [Sum of fifth powers], level: 2)[
Surprisingly, there are only three numbers that can be written as the sum of the fourth powers of their digits:
$
1634 = 1^4 + 6^4 + 3^4 + 4^4\
8208 = 8^4 + 2^4 + 0^4 + 8^4\
9474 = 9^4 + 4^4 + 7^4 + 4^4
$

We do not count $1 = 1^4$ because it is not a sum.

The sum of these numbers is $1634 + 8208 + 9474 = 19316$.

*Find the sum of all numbers that can be written as the sum of the fifth powers of their digits.*

_(Inspired by problem 30 of Project Euler)_
]


#problem-block(number: 31, title: [Swiss coins], level: 3)[
In Switzerland, there are seven coins: $5$ cents, $10$ cents, $20$ cents, $50$ cents, $1$ franc, $2$ francs, and $5$ francs.

You can make $10$ francs like this: $1 times 5 "francs" + 2 times 2 "francs" + 10 times 10 "cents"$.

*How many ways can you make $10$ francs using any number of Swiss coins?*

_(Inspired by problem 31 of Project Euler)_
]


#problem-block(number: 32, title: [Pandigital identities], level: 3)[
The product $7254$ is interesting because the identity $39 times 186 = 7254$, composed in the order of multiplicand, multiplier, and product, uses exactly once all the digits from $1$ to $9$.

Find the sum of all products having this property.

*Warning!* The same product can be obtained in several ways. It should only be counted once in the total.

_(Inspired by problem 32 of Project Euler)_
]


#problem-block(number: 33, title: [Easter in April], level: 2)[
*During the years $2001$ to $9999$ (inclusive), how many times will the date of Easter fall in April, in the Gregorian calendar?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 34, title: [$1! + 4! + 5! = 145$], bm-title: [1! + 4! + 5! = 145], level: 1)[
$145$ is a curious number. Indeed, $1! + 4! + 5! = 1 + 24 + 120 = 145$.

*Find the product of all numbers that are equal to the sum of the factorial of their digits.*

*Notes:*\
1! = 1 and 2! = 2 are not sums and will not be included in the product.\
Remember that 0! = 1.

_(Inspired by problem 34 of Project Euler)_
]


#problem-block(number: 35, title: [Circular prime numbers], level: 3)[
The prime number $197$ is called "circular" because all circular permutations of its digits: $197$, $971$ and $719$ are also prime numbers.

There are $13$ circular prime numbers less than $100$: $2$, $3$, $5$, $7$, $11$, $13$, $17$, $31$, $37$, $71$, $73$, $79$, and $97$.

*How many circular prime numbers are there less than $100 thin 000$?*

_(Inspired by problem 35 of Project Euler)_
]


#problem-block(number: 36, title: [Palindromic numbers in two bases], level: 2)[
The decimal number $585$ ($1001001001$ in binary) is a palindrome in both bases.

*Find the sum of all numbers less than $10$ million that are palindromes in base $10$ and base $2$.*

*Note*: Whether in base $10$ or base $2$, the numbers must not start with a $0$.

_(Inspired by problem 36 of Project Euler)_
]


#problem-block(number: 37, title: [Truncable prime numbers], level: 3)[
The number $3797$ has an interesting property. It is prime, and it remains prime when we eliminate its digits one by one from left to right: $3797$, $797$, $97$ and $7$ are all prime numbers. The same is true when eliminating the digits from right to left: $3797$, $379$, $37$, and $3$ are also all prime numbers.

*Find the sum of the eleven prime numbers that can be truncated from left to right and from right to left.*

*Note*: $2$, $3$, $5$ and $7$ are not considered truncable prime numbers.

_(Inspired by problem 37 of Project Euler)_
]


#problem-block(number: 38, title: [Conway sequence], level: 3)[
The Conway sequence is a mathematical sequence invented in 1986 by mathematician John Horton Conway, initially under the name "audioactive sequence". In this sequence, a term is determined by announcing the digits that form the previous term.

$T_1 = 1$\
$T_2 = 11$\
$T_3 = 21$\
$T_4 = 1211$\
$T_5 = 111221$\
$T_6 = 312211$\
$T_7 = 13112221$\
$T_8 = 1113213211$\
$T_9 = 31131211131221$\
$dots$

If $T_1 = 2$, how many $1$s will there be in $T_50$?

_(Proposed by Le Coyote)_
]


#problem-block(number: 39, title: [Right triangles with given perimeter], level: 3)[
If $p$ is the perimeter of a right triangle with integer side lengths, there are exactly three solutions for $p = 120$: ${20,48,52}$, ${24,45,51}$, ${30,40,50}$.

*For what value of $p < 10 thin 000$ is the number of solutions maximum?*

_(Inspired by problem 39 of Project Euler)_
]


#problem-block(number: 40, title: [Champernowne's constant], level: 2)[
The Champernowne constant is an irrational real number created by concatenating positive integers:
$ 0.12345678910bold(1)112131415161718192021 dots.c $

We can see that the $12$th digit of the fractional part is $1$.

*If $d_n$ represents the $n$th digit of the fractional part, what is the value of the following expression:*
*$ d_1 times d_10 times d_100 times d_1000 times d_10000 times d_100000 times d_1000000 times d_10000000 times d_100000000 $*

_(Inspired by problem 40 of Project Euler)_
]


#problem-block(number: 41, title: [Pandigital prime], level: 3)[
We say that a number with $n$ digits is pandigital if it contains all digits from $1$ to $n$ exactly once. For example, $2143$ is pandigital and is also prime.

*What is the largest pandigital prime number?*

_(Inspired by problem 41 of Project Euler)_
]


#problem-block(number: 42, title: [UN x UN + UN = DEUX], level: 2)[
A cryptarithm is a numerical and logical puzzle consisting of a mathematical equation where letters represent numbers to be found.

*Solve the cryptarithm below (give the answer as the number `DEUX`):*

#align(center)[`UN x UN + UN = DEUX`]

_(Proposed by Le Coyote)_
]


#problem-block(number: 43, title: [Palindrome squares], level: 2)[
A palindromic number reads the same backward as forward. A single-digit number is a palindrome.

*Give the sum of the numbers whose square is a palindrome of at most $13$ digits.*

_(Proposed by Le Coyote)_
]


#problem-block(number: 44, title: [Pentagon numbers], level: 3)[

Pentagonal numbers follow the formula $P_n=n(3n-1)\/2$. The first ten pentagonal numbers are:
$ 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, dots $

We can see that $P_4 + P_7 = 22 + 70 = 92 = P_8$. However, their difference, $70 - 22 = 48$, is not pentagonal.

*Find the two pentagonal numbers $P_j$ and $P_k$, whose sum and difference are pentagonal, and whose $D = |P_k - P_j|$ is minimized.* Give the value of $D$.

_(Inspired by problem 44 of Project Euler)_
]


#problem-block(number: 45, title: [Triangular, pentagonal, and hexagonal], level: 2)[

Triangular, pentagonal, and hexagonal numbers follow these formulas:

Triangular #h(1em) $T_n=n(n+1)\/2: 1, 3, 6, 10, 15, dots$\
Pentagonal #h(1em) $P_n=n(3n-1)\/2: 1, 5, 12, 22, 35, dots$\
Hexagonal #h(1em) $H_n=n(2n-1): 1, 6, 15, 28, 45, dots$

We can verify that $T_285 = P_165 = H_143 = 40755$.

*Find the next triangular number that is also pentagonal and hexagonal.*

_(Inspired by problem 45 of Project Euler)_
]


#problem-block(number: 46, title: [Another conjecture of Goldbach], level: 3)[
Christian Goldbach conjectured that every odd composite number could be written as the sum of a prime number and twice a square number.
$
9 = 7 + 2 times 1^2\
15 = 7 + 2 times 2^2\
21 = 3 + 2 times 3^2\
25 = 7 + 2 times 3^2\
27 = 19 + 2 times 2^2\
33 = 31 + 2 times 1^2
$

It turns out that this conjecture is false.

*What is the smallest odd composite number that contradicts this conjecture?*

_(Inspired by problem 46 of Project Euler)_
]


#problem-block(number: 47, title: [Distinct prime factors], level: 3)[
The first two consecutive numbers with two distinct prime factors are:
$
14 = 2 times 7\
15 = 3 times 5
$

The first three consecutive numbers with three distinct prime factors are:
$
644 = 2^2 times 7 times 23\
645 = 3 times 5 times 43\
646 = 2 times 17 times 19.
$

*Find the first four consecutive numbers with four distinct prime factors. What is the smallest of these numbers?*

_(Inspired by problem 47 of Project Euler)_
]


#problem-block(number: 48, title: [$1^1 + 2^2 + 3^3 + dots.c$], bm-title: [1^1 + 2^2 + 3^3 + ...], level: 1)[
$1^1 + 2^2 + 3^3 + dots.c + 10^10 = 10405071317$.

*Give the first $10$ digits of the series $1^1 + 2^2 + 3^3 + dots.c + 2013^2013$.*

_(Inspired by problem 48 of Project Euler)_
]


#problem-block(number: 49, title: [A very special arithmetic progression...], level: 4)[
The arithmetic progression $1487$, $4817$, $8147$, with a common difference of $3330$, is special for two reasons:
+ all 3 terms are prime;
+ all 3 terms are composed of the same digits

*There is only one other arithmetic progression of $4$-digit numbers with the same properties. Which one?*\
Give the first term multiplied by the common difference as your answer.

_(Inspired by problem 49 of Project Euler)_
]


#problem-block(number: 50, title: [Hamming sequence], level: 3)[
Consider the integers whose only prime divisors are $2$, $3$, and $5$. Arrange them in ascending order. This is the Hamming sequence:
$ 2, 3, 4, 5, 6, 8, 9, 10, 12, 15, 16, 18, 20, 24, 25, 27, 30, 32, 36, 40, 45, 48, 50, dots $

*What is the $2013$#super[th] term in this sequence?*

_(Inspired by puzzle 5 from "Jeux et casse-tête à programmer" by J. Arsac)_
]


#problem-block(number: 51, title: [Swiss Cryptarithm], level: 2)[
A cryptarithm is a numerical and logical puzzle consisting of a mathematical equation in which letters represent numbers to be found.

*Solve the cryptarithm below* (give the sum obtained as the answer):

```
    ARGAND
   + EULER
   -------
    GULDIN
```

Additional information:
- the number $2$ does not appear;
- the number $0$ appears.

_(Proposed by Marie-Pierre Falissard)_
]


#problem-block(number: 52, title: [Multiples contain the same digits], level: 3)[
We can see that the number $125874$ and its double $251748$ contain  the same digits, but in a different order.

*Find the smallest positive integer $n$ such that $n$, $2n$, $3n$, $4n$, $5n$ and $6n$ contain the same digits.*

_(Inspired by problem 52 of Project Euler)_
]


#problem-block(number: 53, title: [Grid of sums], level: 3)[
Consider a square grid with $3$ rows and $3$ columns. We want to fill this grid with whole numbers. To start with, we place the number $20$ in one cell and the number 13 in another. The other cells are filled in one after the other, in an order to be defined. The number placed in a square must be the sum of the numbers in the surrounding squares (i.e., the squares that touch the square to be filled on one side or corner). The largest number placed is called the grid's filling number.

Where should the two starting numbers be placed, and in what order should the grid boxes be filled to obtain the largest possible filling number?

*What is the largest filling number?*

_(#link("http://www.lemonde.fr/sciences/video/2013/04/12/les-defis-mathematiques-du-monde-episode-3-la-grille-de-sommes_3159020_1650684.html")[Les défis mathématiques du Monde, épisode 3])_
]


#problem-block(number: 54, title: [Many $2$s], bm-title: [Many 2s], level: 2)[
Consider the multiplication:

#align(center)[`_ 2 _ _ _ x _ _ = 2222 _ _`]

In this operation, we have written both $2$s (there are no others).

*Find the largest possible multiplicand.*

_(Lewis Carroll Trophy 2013 for high school students)_
]


#problem-block(number: 55, title: [Lychrel numbers], level: 2)[
If we take $47$, reverse it, and add the two numbers together ($47 + 74 = 121$), we get a palindrome, i.e., a natural number that is equal to itself when read from left to right or right to left. The same applies to $20$: $20 + 02 = 22$.\
Not all numbers produce palindromes so quickly. For example, it takes three iterations starting from $349$: $349 + 943 = 1292$, $1292 + 2921 = 4213$, $4213 + 3124 = 7337$.\
There are also numbers, such as $196$, that will never produce a palindrome using this process. These numbers are called "Lychrel numbers".

*Given that $10 thin 677$ is the first number requiring more than $50$ iterations to produce a palindrome, how many Lychrel numbers are there below $10 thin 000$?*

_(Inspired by problem 55 of Project Euler)_
]


#problem-block(number: 56, title: [Maximum sum of digits of a power], level: 2)[
A gogol ($10^100$) is an enormous number: $1$ followed by $100$ zeros. However, the sum of its digits is only $1$.

*Considering natural numbers of the form ab, where $a<250$ and $b<250$, what is the maximum sum of digits that can be obtained?*

_(Inspired by problem 56 of Project Euler)_
]


#problem-block(number: 57, title: [Continued fraction], level: 2)[
The square root of two can be represented by a continued fraction:

$ sqrt(2) = 1 + display(1/(2 + display(1/(2 + display(1/(2 + dots.c)))))) $

The first four iterations give:

$1 + 1\/2 = 3\/2 = 1.5$\
$1 + 1\/(2 + 1\/2) = 7\/5 = 1.4$\
$1 + 1\/(2 + 1\/(2 + 1\/2)) = 17\/12 = 1.41666 dots.c$\
$1 + 1\/(2 + 1\/(2 + 1\/(2 + 1\/2))) = 41\/29 = 1.41379 dots.c$

The next three fractions are $99\/70$, $239\/169$, and $577\/408$. The eighth fraction, 1393/985, is the first one where the numerator has more digits than the denominator.

*Among the first $10 thin 000$ fractions, how many have a numerator with more digits than the denominator?*

_(Inspired by problem 57 of Project Euler)_
]


#problem-block(number: 58, title: [Prime numbers on a spiral], level: 3)[
Starting from $1$ and forming a spiral by turning counterclockwise, we obtain a square with a width of $7$:

#show "red17": text(fill: red, weight: "bold")[17]
#show "red13": text(fill: red, weight: "bold")[13]
#show "red5": text(fill: red, weight: "bold")[5]
#show "red3": text(fill: red, weight: "bold")[3]
#show "red7": text(fill: red, weight: "bold")[7]
#show "red43": text(fill: red, weight: "bold")[43]
#show "red37": text(fill: red, weight: "bold")[37]
#show "red31": text(fill: red, weight: "bold")[31]

#align(center)[
```
red37 36 35 34 33 32 red31
38 red17 16 15 14 red13 30
39 18  red5  4  red3 12 29
40 19  6  1  2 11 28
41 20  red7  8  9 10 27
42 21 22 23 24 25 26
red43 44 45 46 47 48 49
```
]

It is interesting to note that the odd squares are located on the diagonal line starting from 1 towards the lower right corner. It is even more interesting to note that $8$ of the $13$ numbers on the diagonals are prime numbers, representing approximately $62%$ of the prime numbers.\
If we add another layer to the spiral, we will obtain a square with a width of $9$.\
*Continuing this process, for what width of the spiral will there be less than $13%$ prime numbers on the diagonals for the first time?*

_(Inspired by problem 58 of Project Euler)_
]


#problem-block(number: 59, title: [Untouchable numbers], level: 3)[
An untouchable number is a natural number that cannot be expressed as the sum of the proper divisors of an integer (divisors other than the integer itself).

For example, $9$ is not untouchable, because 15 has proper divisors $1$, $3$, $5$, and $1+3+5 = 9$.

On the other hand, $52$ is untouchable because no integer has $52$ as the sum of its proper divisors.

The first untouchable numbers are: $2$, $5$, $52$, $88$, $96$, $120$, $124$, $146$, $162$, $188$, ...

If $k$ is not untouchable, let $p(k)$ be the smallest integer whose sum of proper divisors is $k$. *What is the maximum value of $p(k)$ for $k$ less than $666$?*

_(Proposed by Nicolas Quinodoz)_
]


#problem-block(number: 60, title: [Mass suicide], level: 2)[
The $2013$ members of a cult decided to commit suicide. To perform the funeral ritual, they formed a circle and numbered themselves from $1$ to $2013$.\
They began counting, starting with number $1$. Every $7$th person would have to die. Thus, the first to die will be number $7$, the second number $14$, the third number $21$, and so on.\
You are a member of this cult, but you have no desire to die! Your task is to find the position in the circle that will allow you to be designated last, and thus escape death.

*Which position will save you?*

_(Proposed by "problème de Josèphe")_
]

