#import "../templates/preamble.typ": *


#problem-block(number: 1, title: [Sum of multiples of 5 or 7], level: 1)[
If we list all the natural numbers less than $20$ that are multiples of $5$ or $7$, we get $5$, $7$, $10$, $14$ and $15$. The sum of these numbers is $51$.

*Find the sum of all multiples of $5$ or $7$ less than $2013$.*

_(Inspired by problem 1 of Project Euler)_
]


#problem-block(number: 2, title: [Sum of odd-valued terms in Fibonacci sequence], level: 1)[
Each new term in the Fibonacci sequence is generated by adding the two preceding terms. Starting with $1$ and $1$, the first $10$ terms are as follows:
$ 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, dots $

*By considering the terms in the Fibonacci sequence whose values do not exceed $4$ million, find the sum of the odd-valued terms.*

_(Inspired by problem 2 of Project Euler)_
]


#problem-block(number: 3, title: [Largest prime factor of composite number], level: 1)[
The prime factors of the number $2013$ are $3$, $11$ and $61$, because $3 times 11 times 61 = 2013$.

*What is the largest prime factor of the number $20130101$?*

_(Inspired by problem 3 of Project Euler)_
]


#problem-block(number: 4, title: [Largest palindrome of multiplying two numbers], level: 2)[
A palindromic number reads the same from left to right and from right to left.\
The largest palindrome that can be obtained by multiplying two 2-digit numbers is $9009 = 99 times 91$.

*What is the largest palindrome that can be obtained by multiplying a 4-digit number by a 3-digit number?*

_(Inspired by problem 4 of Project Euler)_
]


#problem-block(number: 5, title: [Sum of digits of $2^2222$], bm-title: [Sum of digits of 2^2222], level: 1)[
$2^15 = 32768$ and the sum of its digits is $3 + 2 + 7 + 6 + 8 = 26$.

*What is the sum of the digits that make up the number $2^2222$?*

_(Inspired by problem 16 of Project Euler)_
]


#problem-block(number: 6, title: [Sum of digits in number $2013!$], bm-title: [Sum of digits in number 2013!], level: 1)[
$n!$ means $n times (n-1) times dots.c times 3 times 2 times 1$.\
For example, $10! = 10 times 9 times dots.c times 3 times 2 times 1 = 3628800$.\
The sum of the digits in the number $10!$ is $3 + 6 + 2 + 8 + 8 + 0 + 0 = 27$.

*Find the sum of the digits in the number $2013!$.*

_(Inspired by problem 20 of Project Euler)_
]


#problem-block(number: 7, title: [What is the $23456$#super[th] prime number?], bm-title: [What is the 23456th prime number?], level: 2)[
By listing the first six prime numbers: $2$, $3$, $5$, $7$, $11$ and $13$, we see that the $6$#super[th] prime number is $13$.

*What is the $23456$#super[th] prime number?*

_(Inspired by problem 7 of Project Euler)_
]


#problem-block(number: 8, title: [Rectangle-$6400$], bm-title: [Rectangle-6400], level: 3)[
In a rectangle with a length of $4$ and a width of $3$, we can draw $12$ squares with a side length of $1$, $6$ squares with a side length of $2$, and $2$ squares with a side length of $3$. In total, we can draw $20$ squares. We will call this a rectangle-$20$.

*What is the area of ​​the rectangle-$6400$ whose shape is closest to a square?*

Note: The dimensions are whole numbers for both the rectangle and the squares.

_(Inspired by the 2012 CMP problem from the mathematics and physics circle of the Société jurassienne d'émulation)_
]


#problem-block(number: 9, title: [Pythagorean triplet], level: 2)[
A triplet of non-zero natural numbers $(a, b, c)$ is Pythagorean if $a^2 + b^2 = c^2$. For example, $(3, 4, 5)$ is a Pythagorean triplet.

*Among the Pythagorean triples $(a, b, c)$ such that $a + b + c = 3600$, give the largest product $a times b times c$.*

_(Inspired by problem 9 of Project Euler)_
]


#problem-block(number: 10, title: [Sum of prime numbers], level: 2)[
The sum of the prime numbers between $1$ and $10$ is $2 + 3 + 5 + 7 = 17$.

*Find the sum of the prime numbers between $1$ and $10 thin 000 thin 000$.*

_(Inspired by problem 10 of Project Euler)_
]


#problem-block(number: 11, title: [Mirror of number], level: 1)[
The "mirror image of a number $n$" is the number $n$ written from right to left. For example, $op("mirror")(7423) = 3247$.

*What is the largest number less than $10$ million that has the property: $op("mirror")(n) = 4 times n$?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 12, title: [Triangular numbers with many divisors], level: 3)[
The sequence of triangular numbers is generated by adding the natural numbers. Thus, the $7$#super[th] triangular number is $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten triangular numbers are as follows:
$ 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, dots $

Let us list the divisors of the first seven triangular numbers:
$
1 &: 1\
3 &: 1, 3\
6 &: 1, 2, 3, 6\
10 &: 1, 2, 5, 10\
15 &: 1, 3, 5, 15\
21 &: 1, 3, 7, 21\
28 &: 1, 2, 4, 7, 14, 28
$

We can see that $28$ is the first triangular number with more than five divisors.

*What is the value of the first triangular number with more than one thousand divisors?*

_(Inspired by problem 12 of Project Euler)_
]


#problem-block(number: 13, title: [Palindrome square], level: 1)[
The smallest palindromic square with an even number of digits is $698896 = 836^2$.

*What is the next palindromic square?*

_(Source: The Mathematical Gazette)_
]


#problem-block(number: 14, title: [Longest Syracuse sequence], level: 1)[
In mathematics, a "Syracuse sequence" is a sequence of natural numbers defined as follows:

We start with an integer greater than zero; if it is even, we divide it by $2$; if it is odd, we multiply it by $3$ and add $1$.\
By repeating the operation, we obtain a sequence of positive integers, each of which depends only on its predecessor.

There is a conjecture that says that the Syracuse sequence of any strictly positive integer reaches $1$.

For example, starting from 14, we construct the sequence of numbers: $14$, $7$, $22$, $11$, $34$, $17$, $52$, $26$, $13$, $40$, $20$, $10$, $5$, $16$, $8$, $4$, $2$, $1$. This is called the Syracuse sequence of the number $14$. Here, it has a length of $18$.

*For what starting number less than $1 thin 500 thin 000$ do we obtain the longest Syracuse sequence?* There are two solutions, give the smallest one.

_(Inspired by problem 14 of Project Euler)_
]


#problem-block(number: 15, title: [Numbers of Mage Hic], level: 3)[
Fill in a $3 times 3$ grid with all the numbers from $1$ to $9$ (green squares). Then calculate the products of the three numbers in each row and each column (grey squares). Finally, add these six products together to obtain the blue number ($450$ in the example given).

#align(center)[
  #v(0.5em)
  #image(width: 100pt, "../figures/015.png")
  #v(0.5em)
]

*Of the $362 thin 880$ possible grids, what is the minimum blue number and the maximum blue number? Give the product of these two numbers as the result.*

_(Inspired by problem 12 from the 2013 FFJM individual quarterfinals: "Le nombre du Mage Hic")_
]


#problem-block(number: 16, title: [THREE x NINE = TROIS x NEUF], level: 3)[
A cryptarithm is a numerical and logical puzzle consisting of a mathematical equation in which letters represent numbers to be found. Each different letter represents a different number, and each number is represented by the same letter.

*Solve the cryptarithm below* (give the product obtained as the answer):

#align(center)[`THREE x NINE = TROIS x NEUF`]

*Constraints:*\
`THREE` and `NEUF` are multiples of $9$;\
`TROIS` and `NINE` are multiples of $3$.

_(Problem 18 from the quarterfinals of the 2003 mathematical and logical games)_
]


#problem-block(number: 17, title: [Amicable numbers], level: 3)[
Let $d(n)$ be the sum of the proper divisors of $n$ (divisors strictly smaller than $n$). If $d(a)=b$ and $d(b)=a$, with a different from $b$, then $a$ and $b$ are said to be amicable.\
For example, the proper divisors of $220$ are $1$, $2$, $4$, $5$, $10$, $11$, $20$, $22$, $44$, $55$ and $110$; therefore $d(220) = 284$. The proper divisors of $284$ are $1$, $2$, $4$, $71$ and $142$; therefore $d(284) = 220$. $220$ and $284$ are two amicable numbers.\
The sum of the amicable numbers between $1$ and $1000$ is $220 + 284 = 504$.

*What is the sum of the amicable numbers between $1$ and $100 thin 000$?*

_(Inspired by problem 21 of Project Euler)_
]


#problem-block(number: 18, title: [Sum of non-abundant numbers], level: 3)[
A perfect number is a number whose sum of proper divisors is exactly equal to the number itself. For example, the sum of the proper divisors of 28 would be $1 + 2 + 4 + 7 + 14 = 28$, which means that $28$ is a perfect number.

A number $n$ is called deficient if the sum of its proper divisors is less than $n$, and it is called abundant if this sum is greater than $n$.

Since $12$ is the smallest abundant number ($1 + 2 + 3 + 4 + 6 = 16$), the smallest number that can be written as the sum of two abundant numbers is $24$.

*Find the sum of all positive integers less than or equal to $2013$ that #underline[cannot] be written as the sum of two abundant numbers.*

_(Inspired by problem 23 of Project Euler)_
]


#problem-block(number: 19, title: [Close encounters of the fourth kind], level: 1)[
Little green men meet little blue men. To their great surprise, they notice that their hands do not have the same number of fingers: $7$ for the blue ones and $8$ for the green ones. But the scientists of both peoples notice that if you count on your fingers as shown in the figure, moving back and forth from the little finger to the thumb, then from the thumb to the little finger, certain numbers can be counted on both the ring finger of the blue hands and the ring finger of the green hands ($2$ and $14$, for example).\
These numbers have been termed "annular" by scholars.

#align(center)[
  #v(0.5em)
  #image(width: 300pt, "../figures/019.jpg")
  #v(0.5em)
]

*Calculate the sum of the ring numbers between $1$ and $2013$.*

_(Inspired by a problem from the Mathematical and Logical Games Championship)_
]


#problem-block(number: 20, title: [Hercules and the hydra], level: 3)[
A battle between Hercules and one (or more) hydra(s) can be described by the following steps:
- On the first blow, the Hydra loses a head, and a copy of the wounded Hydra (that is, one with one less head) appears. On the second blow, a Hydra loses a head, and two copies of the wounded Hydra appear. On the tenth blow, a Hydra loses a head, so ten copies appear, and so on.
- When a one-headed Hydra is struck, it disappears.
- To complicate matters, the treacherous Hera forces Hercules to cut off the heads in the worst possible order, so that it takes him as long as possible to destroy the Hydras.

#align(center)[
  #v(0.5em)
  #image(width: 240pt, "../figures/020.gif")
  Example: Hercules fights two two-headed hydras and two one-headed hydras.
  #v(0.5em)
]

*Assuming Hercules is capable of cutting off a head every second, how many seconds will it take him to defeat a four-headed hydra?*

_(Jean-Bernard Roux's problem)_
]


#problem-block(number: 21, title: [Happy new year 2013!], level: 2)[
$2013$ has an interesting feature: it is the first year since $1987$ to be composed of all different digits. A period of $26$ years separates these two dates.

*Between year $1$ and $2013$ (inclusive):*

*a) How many years have there been with all different digits? (Years $1$ through $9$ will be counted in this number).*\
*b) What was the length (in years) of the longest period between two dates with all different digits?*

*Give the product of the results of a) and b).*

_(Proposed by Le Coyote)_
]


#problem-block(number: 22, title: [Eightfold anagrams], level: 2)[
Mathilde found two surprising six-digit numbers. When multiplied by $8$, they produce a six-digit number written with the same digits in a different order. Even better: these two numbers are also anagrams!

*What are Mathilde's numbers?* Give the sum of the two numbers.

_(Inspired by problem 14 from the quarterfinals of the 2010 Mathematical and Logical Games)_
]


#problem-block(number: 23, title: [Paths in a grid], level: 2)[
Starting from the top left corner of a $2 times 2$ grid, there are $6$ paths to the bottom right corner, moving only to the right or down.

#align(center)[
  #v(0.5em)
  #image(width: 150pt, "../figures/023.gif")
  #v(0.5em)
]

*How many such paths are there in a $30 times 20$ grid?*

_(Inspired by problem 15 of Project Euler)_
]


#problem-block(number: 24, title: [Lexicographic permutations], level: 2)[
A permutation is an ordered arrangement of objects. For example, $3124$ is a possible permutation of the digits $1$, $2$, $3$ and $4$.\
The list of permutations in lexicographical order of $0$, $1$ and $2$ is as follows:
$ 012, 021, 102, 120, 201, 210 $

*In lexicographical order, what is the two-millionth permutation of the digits $0$, $1$, $2$, $3$, $4$, $5$, $6$, $7$, $8$, $9$?*

_(Inspired by problem 24 of Project Euler)_
]


#problem-block(number: 25, title: [First Fibonacci number with $2013$ digits], bm-title: [First Fibonacci number with 2013 digits], level: 1)[
The Fibonacci sequence is defined by the recurrence relation:
$ F_n = F_(n-1) + F_(n-2), "where" F_1 = 1 "and" F_2 = 1. $

Thus, the first $12$ terms are: $1$, $1$, $2$, $3$, $5$, $8$, $13$, $21$, $34$, $55$, $89$, $144$, ...\
The $12$th term, $F_12$, is the first term that contains $3$ digits.

*What is the index of the first term in the Fibonacci sequence that contains $2013$ digits?*

_(Inspired by problem 25 of Project Euler)_
]


#problem-block(number: 26, title: [Number divisible by pieces], level: 3)[
*Find an integer $c_1 c_2 c_3 dots.c c_9$ composed of all digits from $1$ to $9$, such that $c_1 dots.c c_k$ is divisible by $k$, for $k=1,dots,9$.*

Let's take a $3$-digit example: $321$.

$3$ is divisible by $1$.\
$32$ is divisible by $2$.\
$321$ is divisible by $3$.

_(Source unknown)_
]


#problem-block(number: 27, title: [Euler's polynomial for prime numbers], level: 3)[
Euler published the remarkable quadratic polynomial:
$ n^2 + n + 41 $

It turns out that this formula provides $40$ prime numbers for successive values of $n$ ranging from $0$ to $39$. However, when $n=40$, $40^2+40+41 = 40(40+1)+41$ is divisible by $41$.

Using a computer, the incredible formula $n^2 - 79 n + 1601$ was discovered. It provides $80$ prime numbers for successive values of $n$ ranging from $0$ to $79$ (each prime number appears twice):

$1601$, $1523$, $1447$, $1373$, $1301$, $1231$, $1163$, $1097$, $1033$, $971$, $911$, $853$, $797$, $743$, $691$, $641$, $593$, $547$, $503$, $461$, $421$, $383$, $347$, $313$, $281$, $251$, $223$, $197$, $173$, $151$, $131$, $113$, $97$, $83$, $71$, $61$, $53$, $47$, $43$, $41$, $41$, $43$, $47$, $53$, $61$, $71$, $83$, $97$, $113$, $131$, $151$, $173$, $197$, $223$, $251$, $281$, $313$, $347$, $383$, $421$, $461$, $503$, $547$, $593$, $641$, $691$, $743$, $797$, $853$, $911$, $971$, $1033$, $1097$, $1163$, $1231$, $1301$, $1373$, $1447$, $1523$, $1601$.


The product of the coefficients, $-79$ and $1601$, gives $-126479$.

Consider quadratic polynomials of the form:\
$n^2 + a n + b, "where" |a| < 1500 "and" |b| < 1500$\
where $|n|$ is the absolute value of $n$ (for example, $|11| = 11$ and $|-4| = 4$).

*Give the product of the coefficients $a$ and $b$ of the quadratic polynomial that generates the longest sequence of prime numbers for successive values of n, starting from $n=0$.*

_(Inspired by problem 27 of Project Euler)_
]


#problem-block(number: 28, title: [Spiral numbers], level: 2)[
Starting with the number $1$, and turning clockwise, a $5 times 5$ spiral is constructed as follows:

#show "red21": text(fill: red, weight: "bold")[21]
#show "red25": text(fill: red, weight: "bold")[25]
#show "red7": text(fill: red, weight: "bold")[7]
#show "red9": text(fill: red, weight: "bold")[9]
#show "red1": text(fill: red, weight: "bold")[1]
#show "red5": text(fill: red, weight: "bold")[5]
#show "red3": text(fill: red, weight: "bold")[3]
#show "red17": text(fill: red, weight: "bold")[17]
#show "red13": text(fill: red, weight: "bold")[13]

#align(center)[
```
red21 22 23 24 red25
20  red7  8  red9 10
19  6  red1  2 11
18  red5  4  red3 12
red17 16 15 14 red13
```
]

We can verify that the sum of the numbers on the diagonals is $101$.

*What is the sum of the numbers on the diagonals of a $2013 times 2013$ spiral constructed in the same way?*

_(Inspired by problem 28 of Project Euler)_
]


#problem-block(number: 29, title: [Distinct powers], level: 2)[
Consider $a^b$ for $2 <= a <= 5$ and $2 <= b <= 5$:
$
2^2=4, 2^3=8, 2^4=16, 2^5=32\
3^2=9, 3^3=27, 3^4=81, 3^5=243\
4^2=16, 4^3=64, 4^4=256, 4^5=1024\
5^2=25, 5^3=125, 5^4=625, 5^5=3125
$

If we sort these numbers in ascending order, removing any duplicates, we obtain a sequence of $15$ distinct terms:
$ 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125 $

*How many distinct terms are there in the sequence obtained as above for $2 <= a <= 1000$ and $2 <= b <= 1000$?*

_(Inspired by problem 29 of Project Euler)_
]


#problem-block(number: 30, title: [Sum of fifth powers], level: 2)[
Surprisingly, there are only three numbers that can be written as the sum of the fourth powers of their digits:
$
1634 &= 1^4 + 6^4 + 3^4 + 4^4\
8208 &= 8^4 + 2^4 + 0^4 + 8^4\
9474 &= 9^4 + 4^4 + 7^4 + 4^4
$

We do not count $1 = 1^4$ because it is not a sum.

The sum of these numbers is $1634 + 8208 + 9474 = 19316$.

*Find the sum of all numbers that can be written as the sum of the fifth powers of their digits.*

_(Inspired by problem 30 of Project Euler)_
]


#problem-block(number: 31, title: [Swiss coins], level: 3)[
In Switzerland, there are seven coins: $5$ cents, $10$ cents, $20$ cents, $50$ cents, $1$ franc, $2$ francs, and $5$ francs.

You can make $10$ francs like this: $1 times 5 "francs" + 2 times 2 "francs" + 10 times 10 "cents"$.

*How many ways can you make $10$ francs using any number of Swiss coins?*

_(Inspired by problem 31 of Project Euler)_
]


#problem-block(number: 32, title: [Pandigital identities], level: 3)[
The product $7254$ is interesting because the identity $39 times 186 = 7254$, composed in the order of multiplicand, multiplier, and product, uses exactly once all the digits from $1$ to $9$.

Find the sum of all products having this property.

*Warning!* The same product can be obtained in several ways. It should only be counted once in the total.

_(Inspired by problem 32 of Project Euler)_
]


#problem-block(number: 33, title: [Easter in April], level: 2)[
*During the years $2001$ to $9999$ (inclusive), how many times will the date of Easter fall in April, in the Gregorian calendar?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 34, title: [$1! + 4! + 5! = 145$], bm-title: [1! + 4! + 5! = 145], level: 1)[
$145$ is a curious number. Indeed, $1! + 4! + 5! = 1 + 24 + 120 = 145$.

*Find the product of all numbers that are equal to the sum of the factorial of their digits.*

*Notes:*\
1! = 1 and 2! = 2 are not sums and will not be included in the product.\
Remember that 0! = 1.

_(Inspired by problem 34 of Project Euler)_
]


#problem-block(number: 35, title: [Circular prime numbers], level: 3)[
The prime number $197$ is called "circular" because all circular permutations of its digits: $197$, $971$ and $719$ are also prime numbers.

There are $13$ circular prime numbers less than $100$: $2$, $3$, $5$, $7$, $11$, $13$, $17$, $31$, $37$, $71$, $73$, $79$, and $97$.

*How many circular prime numbers are there less than $100 thin 000$?*

_(Inspired by problem 35 of Project Euler)_
]


#problem-block(number: 36, title: [Palindromic numbers in two bases], level: 2)[
The decimal number $585$ ($1001001001$ in binary) is a palindrome in both bases.

*Find the sum of all numbers less than $10$ million that are palindromes in base $10$ and base $2$.*

*Note*: Whether in base $10$ or base $2$, the numbers must not start with a $0$.

_(Inspired by problem 36 of Project Euler)_
]


#problem-block(number: 37, title: [Truncable prime numbers], level: 3)[
The number $3797$ has an interesting property. It is prime, and it remains prime when we eliminate its digits one by one from left to right: $3797$, $797$, $97$ and $7$ are all prime numbers. The same is true when eliminating the digits from right to left: $3797$, $379$, $37$, and $3$ are also all prime numbers.

*Find the sum of the eleven prime numbers that can be truncated from left to right and from right to left.*

*Note*: $2$, $3$, $5$ and $7$ are not considered truncable prime numbers.

_(Inspired by problem 37 of Project Euler)_
]


#problem-block(number: 38, title: [Conway sequence], level: 3)[
The Conway sequence is a mathematical sequence invented in 1986 by mathematician John Horton Conway, initially under the name "audioactive sequence". In this sequence, a term is determined by announcing the digits that form the previous term.

$
T_1 &= 1\
T_2 &= 11\
T_3 &= 21\
T_4 &= 1211\
T_5 &= 111221\
T_6 &= 312211\
T_7 &= 13112221\
T_8 &= 1113213211\
T_9 &= 31131211131221\
&dots
$

If $T_1 = 2$, how many $1$s will there be in $T_50$?

_(Proposed by Le Coyote)_
]


#problem-block(number: 39, title: [Right triangles with given perimeter], level: 3)[
If $p$ is the perimeter of a right triangle with integer side lengths, there are exactly three solutions for $p = 120$: ${20,48,52}$, ${24,45,51}$, ${30,40,50}$.

*For what value of $p < 10 thin 000$ is the number of solutions maximum?*

_(Inspired by problem 39 of Project Euler)_
]


#problem-block(number: 40, title: [Champernowne's constant], level: 2)[
The Champernowne constant is an irrational real number created by concatenating positive integers:
$ 0.12345678910bold(1)112131415161718192021 dots.c $

We can see that the $12$th digit of the fractional part is $1$.

*If $d_n$ represents the $n$th digit of the fractional part, what is the value of the following expression:*
*$ d_1 times d_10 times d_100 times d_1000 times d_10000 times d_100000 times d_1000000 times d_10000000 times d_100000000 $*

_(Inspired by problem 40 of Project Euler)_
]


#problem-block(number: 41, title: [Pandigital prime], level: 3)[
We say that a number with $n$ digits is pandigital if it contains all digits from $1$ to $n$ exactly once. For example, $2143$ is pandigital and is also prime.

*What is the largest pandigital prime number?*

_(Inspired by problem 41 of Project Euler)_
]


#problem-block(number: 42, title: [UN x UN + UN = DEUX], level: 2)[
A cryptarithm is a numerical and logical puzzle consisting of a mathematical equation where letters represent numbers to be found.

*Solve the cryptarithm below (give the answer as the number `DEUX`):*

#align(center)[`UN x UN + UN = DEUX`]

_(Proposed by Le Coyote)_
]


#problem-block(number: 43, title: [Palindrome squares], level: 2)[
A palindromic number reads the same backward as forward. A single-digit number is a palindrome.

*Give the sum of the numbers whose square is a palindrome of at most $13$ digits.*

_(Proposed by Le Coyote)_
]


#problem-block(number: 44, title: [Pentagon numbers], level: 3)[

Pentagonal numbers follow the formula $P_n=n(3n-1)\/2$. The first ten pentagonal numbers are:
$ 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, dots $

We can see that $P_4 + P_7 = 22 + 70 = 92 = P_8$. However, their difference, $70 - 22 = 48$, is not pentagonal.

*Find the two pentagonal numbers $P_j$ and $P_k$, whose sum and difference are pentagonal, and whose $D = |P_k - P_j|$ is minimized.* Give the value of $D$.

_(Inspired by problem 44 of Project Euler)_
]


#problem-block(number: 45, title: [Triangular, pentagonal, and hexagonal], level: 2)[

Triangular, pentagonal, and hexagonal numbers follow these formulas:

Triangular #h(1em) $T_n=n(n+1)\/2: 1, 3, 6, 10, 15, dots$\
Pentagonal #h(1em) $P_n=n(3n-1)\/2: 1, 5, 12, 22, 35, dots$\
Hexagonal #h(1em) $H_n=n(2n-1): 1, 6, 15, 28, 45, dots$

We can verify that $T_285 = P_165 = H_143 = 40755$.

*Find the next triangular number that is also pentagonal and hexagonal.*

_(Inspired by problem 45 of Project Euler)_
]


#problem-block(number: 46, title: [Another conjecture of Goldbach], level: 3)[
Christian Goldbach conjectured that every odd composite number could be written as the sum of a prime number and twice a square number.
$
9 &= 7 + 2 times 1^2\
15 &= 7 + 2 times 2^2\
21 &= 3 + 2 times 3^2\
25 &= 7 + 2 times 3^2\
27 &= 19 + 2 times 2^2\
33 &= 31 + 2 times 1^2
$

It turns out that this conjecture is false.

*What is the smallest odd composite number that contradicts this conjecture?*

_(Inspired by problem 46 of Project Euler)_
]


#problem-block(number: 47, title: [Distinct prime factors], level: 3)[
The first two consecutive numbers with two distinct prime factors are:
$
14 &= 2 times 7\
15 &= 3 times 5
$

The first three consecutive numbers with three distinct prime factors are:
$
644 &= 2^2 times 7 times 23\
645 &= 3 times 5 times 43\
646 &= 2 times 17 times 19.
$

*Find the first four consecutive numbers with four distinct prime factors. What is the smallest of these numbers?*

_(Inspired by problem 47 of Project Euler)_
]


#problem-block(number: 48, title: [$1^1 + 2^2 + 3^3 + dots.c$], bm-title: [1^1 + 2^2 + 3^3 + ...], level: 1)[
$1^1 + 2^2 + 3^3 + dots.c + 10^10 = 10405071317$.

*Give the first $10$ digits of the series $1^1 + 2^2 + 3^3 + dots.c + 2013^2013$.*

_(Inspired by problem 48 of Project Euler)_
]


#problem-block(number: 49, title: [A very special arithmetic progression...], level: 4)[
The arithmetic progression $1487$, $4817$, $8147$, with a common difference of $3330$, is special for two reasons:
+ all 3 terms are prime;
+ all 3 terms are composed of the same digits

*There is only one other arithmetic progression of $4$-digit numbers with the same properties. Which one?*\
Give the first term multiplied by the common difference as your answer.

_(Inspired by problem 49 of Project Euler)_
]


#problem-block(number: 50, title: [Hamming sequence], level: 3)[
Consider the integers whose only prime divisors are $2$, $3$, and $5$. Arrange them in ascending order. This is the Hamming sequence:
$ 2, 3, 4, 5, 6, 8, 9, 10, 12, 15, 16, 18, 20, 24, 25, 27, 30, 32, 36, 40, 45, 48, 50, dots $

*What is the $2013$#super[th] term in this sequence?*

_(Inspired by puzzle 5 from "Jeux et casse-tête à programmer" by J. Arsac)_
]


#problem-block(number: 51, title: [Swiss Cryptarithm], level: 2)[
A cryptarithm is a numerical and logical puzzle consisting of a mathematical equation in which letters represent numbers to be found.

*Solve the cryptarithm below* (give the sum obtained as the answer):

#align(center)[
```
 ARGAND
+ EULER
-------
 GULDIN
```
]

Additional information:
- the number $2$ does not appear;
- the number $0$ appears.

_(Proposed by Marie-Pierre Falissard)_
]


#problem-block(number: 52, title: [Multiples contain the same digits], level: 3)[
We can see that the number $125874$ and its double $251748$ contain  the same digits, but in a different order.

*Find the smallest positive integer $n$ such that $n$, $2n$, $3n$, $4n$, $5n$ and $6n$ contain the same digits.*

_(Inspired by problem 52 of Project Euler)_
]


#problem-block(number: 53, title: [Grid of sums], level: 3)[
Consider a square grid with $3$ rows and $3$ columns. We want to fill this grid with whole numbers. To start with, we place the number $20$ in one cell and the number 13 in another. The other cells are filled in one after the other, in an order to be defined. The number placed in a square must be the sum of the numbers in the surrounding squares (i.e., the squares that touch the square to be filled on one side or corner). The largest number placed is called the grid's filling number.

Where should the two starting numbers be placed, and in what order should the grid boxes be filled to obtain the largest possible filling number?

*What is the largest filling number?*

_(#link("http://www.lemonde.fr/sciences/video/2013/04/12/les-defis-mathematiques-du-monde-episode-3-la-grille-de-sommes_3159020_1650684.html")[Les défis mathématiques du Monde, épisode 3])_
]


#problem-block(number: 54, title: [Many $2$s], bm-title: [Many 2s], level: 2)[
Consider the multiplication:

#align(center)[`_ 2 _ _ _ x _ _ = 2222 _ _`]

In this operation, we have written both $2$s (there are no others).

*Find the largest possible multiplicand.*

_(Lewis Carroll Trophy 2013 for high school students)_
]


#problem-block(number: 55, title: [Lychrel numbers], level: 2)[
If we take $47$, reverse it, and add the two numbers together ($47 + 74 = 121$), we get a palindrome, i.e., a natural number that is equal to itself when read from left to right or right to left. The same applies to $20$: $20 + 02 = 22$.\
Not all numbers produce palindromes so quickly. For example, it takes three iterations starting from $349$: $349 + 943 = 1292$, $1292 + 2921 = 4213$, $4213 + 3124 = 7337$.\
There are also numbers, such as $196$, that will never produce a palindrome using this process. These numbers are called "Lychrel numbers".

*Given that $10 thin 677$ is the first number requiring more than $50$ iterations to produce a palindrome, how many Lychrel numbers are there below $10 thin 000$?*

_(Inspired by problem 55 of Project Euler)_
]


#problem-block(number: 56, title: [Maximum sum of digits of a power], level: 2)[
A gogol ($10^100$) is an enormous number: $1$ followed by $100$ zeros. However, the sum of its digits is only $1$.

*Considering natural numbers of the form ab, where $a<250$ and $b<250$, what is the maximum sum of digits that can be obtained?*

_(Inspired by problem 56 of Project Euler)_
]


#problem-block(number: 57, title: [Continued fraction], level: 2)[
The square root of two can be represented by a continued fraction:

$ sqrt(2) = 1 + display(1/(2 + display(1/(2 + display(1/(2 + dots.c)))))) $

The first four iterations give:
$
&1 + 1\/2 = 3\/2 = 1.5\
&1 + 1\/(2 + 1\/2) = 7\/5 = 1.4\
&1 + 1\/(2 + 1\/(2 + 1\/2)) = 17\/12 = 1.41666 dots.c\
&1 + 1\/(2 + 1\/(2 + 1\/(2 + 1\/2))) = 41\/29 = 1.41379 dots.c
$

The next three fractions are $99\/70$, $239\/169$, and $577\/408$. The eighth fraction, 1393/985, is the first one where the numerator has more digits than the denominator.

*Among the first $10 thin 000$ fractions, how many have a numerator with more digits than the denominator?*

_(Inspired by problem 57 of Project Euler)_
]


#problem-block(number: 58, title: [Prime numbers on a spiral], level: 3)[
Starting from $1$ and forming a spiral by turning counterclockwise, we obtain a square with a width of $7$:

#show "red17": text(fill: red, weight: "bold")[17]
#show "red13": text(fill: red, weight: "bold")[13]
#show "red5": text(fill: red, weight: "bold")[5]
#show "red3": text(fill: red, weight: "bold")[3]
#show "red7": text(fill: red, weight: "bold")[7]
#show "red43": text(fill: red, weight: "bold")[43]
#show "red37": text(fill: red, weight: "bold")[37]
#show "red31": text(fill: red, weight: "bold")[31]

#align(center)[
```
red37 36 35 34 33 32 red31
38 red17 16 15 14 red13 30
39 18  red5  4  red3 12 29
40 19  6  1  2 11 28
41 20  red7  8  9 10 27
42 21 22 23 24 25 26
red43 44 45 46 47 48 49
```
]

It is interesting to note that the odd squares are located on the diagonal line starting from 1 towards the lower right corner. It is even more interesting to note that $8$ of the $13$ numbers on the diagonals are prime numbers, representing approximately $62%$ of the prime numbers.\
If we add another layer to the spiral, we will obtain a square with a width of $9$.\
*Continuing this process, for what width of the spiral will there be less than $13%$ prime numbers on the diagonals for the first time?*

_(Inspired by problem 58 of Project Euler)_
]


#problem-block(number: 59, title: [Untouchable numbers], level: 3)[
An untouchable number is a natural number that cannot be expressed as the sum of the proper divisors of an integer (divisors other than the integer itself).

For example, $9$ is not untouchable, because 15 has proper divisors $1$, $3$, $5$, and $1+3+5 = 9$.

On the other hand, $52$ is untouchable because no integer has $52$ as the sum of its proper divisors.

The first untouchable numbers are: $2$, $5$, $52$, $88$, $96$, $120$, $124$, $146$, $162$, $188$, ...

If $k$ is not untouchable, let $p(k)$ be the smallest integer whose sum of proper divisors is $k$. *What is the maximum value of $p(k)$ for $k$ less than $666$?*

_(Proposed by Nicolas Quinodoz)_
]


#problem-block(number: 60, title: [Mass suicide], level: 2)[
The $2013$ members of a cult decided to commit suicide. To perform the funeral ritual, they formed a circle and numbered themselves from $1$ to $2013$.\
They began counting, starting with number $1$. Every $7$th person would have to die. Thus, the first to die will be number $7$, the second number $14$, the third number $21$, and so on.\
You are a member of this cult, but you have no desire to die! Your task is to find the position in the circle that will allow you to be designated last, and thus escape death.

*Which position will save you?*

_(Proposed by "problème de Josèphe")_
]


#problem-block(number: 61, title: [No to isolation!], level: 2)[
A digit is isolated if its left and right neighbors are different from itself. For example, in $776444$, $6$ is isolated, but the other digits are not.

On the other hand, the first three numbers that are not multiples of $10$ whose squares contain no isolated digits are:
$
88^2 &= 7744\
74162^2 &= 5500002244\
105462^2 &= 11122233444
$

*What is the fourth?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 62, title: [Cubic permutations], level: 3)[
The digits of the cube $41063625$ ($345^3$) can be permuted to produce two other cubes: $56623104$ ($384^3$) and $66430125$ ($405^3$). In fact, $41063625$ is the smallest cube with this property.

*Find the smallest cube for which exactly four permutations of its digits are cubes.*

Note: the cube itself + $3$ permutations of its digits.

_(Inspired by problem 62 of Project Euler)_
]


#problem-block(number: 63, title: [$x^n$ gives an $n$-digit number], bm-title: [x^n gives an n-digit number], level: 3)[
The $5$-digit number $16807=7^5$ is also a number raised to the power of $5$. Similarly, the $9$-digit number $134217728=8^9$ is a number raised to the power of $9$.

*How many positive integers with $n$ digits are also numbers raised to the power of $n$?*

_(Inspired by problem 63 of Project Euler)_
]


#problem-block(number: 64, title: [Multiplicative persistence], level: 2)[
Consider a positive integer, for example, $377$. Multiply its digits: $3 times 7 times 7 = 147$. Do the same with the result $147$: $1 times 4 times 7 = 28$. Repeat: $2 times 8 = 16$. Again: $1 times 6 = 6$. Once we reach a single-digit number, we stop.

$377$, $147$, $28$, $16$, $6$ is the "multiplicative sequence" of $377$, and the "multiplicative persistence" $p$ of $377$ is the number of times the digits had to be multiplied before arriving at a single-digit number; here, $p$ = 4.

We conjecture that $p$ cannot exceed $11$...

*What is the smallest integer less than $1 thin 000 thin 000$ with the largest multiplicative persistence $p$?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 65, title: [The numbers of the year 2014], level: 2)[
If we add the product of its four digits to the number $2014$: $2014 + 2 times 0 times 1 times 4$, we get $2014$.

*Find the sum of the other positive integers that add up to $2014$ when you add the product of their digits.*

_(Individual quarterfinals of the 28th Mathematical and Logic Games Championship)_
]


#problem-block(number: 66, title: [Period in the decimal expansion], level: 3)[
A unit fraction is a rational number written as a fraction where the numerator is $1$ and the denominator is a positive integer.

$
1\/2 &= 0.5\
1\/3 &= 0.(3)\
1\/4 &= 0.25\
1\/5 &= 0.2\
1\/6 &= 0.1(6)\
1\/7 &= 0.(142857)\
1\/8 &= 0.125\
1\/9 &= 0.(1)\
1\/10 &= 0.1
$

$0.1(6)$ means $0.166666 dots.c$, and $1\/6$ has a period of $1$ digit in its decimal expansion. We can see that $1\/7$ has a period of $6$ digits, while $1\/2$ has no period.

*Find the value of $d<5000$, where $1\/d$ has the longest period in its decimal expansion.*

_(Inspired by problem 26 of Project Euler)_
]


#problem-block(number: 67, title: [Stern's diatomic sequence], level: 1)[
Stern's diatomic sequence is the result of the following small equations:
$
s_0 &= 0\
s_1 &= 1\
s_(2n) &= s_n\
s_(2n+1) &= s_n + s_(n+1)
$

What is the value of $s_(10 thin 000 thin 001)$?

_(Proposed by Le Coyote)_
]


#problem-block(number: 68, title: [SIX#super[2] = TROIS], bm-title: [SIX² = TROIS], level: 2)[
A cryptarithm is a numerical and logical puzzle consisting of a mathematical equation in which letters represent numbers to be found.

#align(center)[`SIX² = TROIS`]

*What is the value of `TROIS`?*

_(Berloquin et al., "Voulez-vous jouer avec nous?", Ballard, 1975)_
]


#problem-block(number: 69, title: [Euler's function], level: 3)[
Two integers are relatively prime if their greatest common divisor is $1$. For example, $8$ and $15$ are relatively prime.\
Euler's function, $phi(n)$, is used to determine the number of integers smaller than n that are relatively prime to $n$. For example, since $1$, $2$, $4$, $5$, $7$, and 8 are all smaller than $9$ and relatively prime to 9, $phi(9)=6$.

#align(center)[
  #v(0.5em)
  #table(
    align: left,
    columns: (auto,)*4,
    stroke: black + 0.75pt,
    [$bold(n)$], [*Relatively Prime*], [$bold(phi(n))$], [$bold(n\/phi(n))$],
    [$2$], [$1$], [$1$], [$2$],
    [$3$], [$1,2$], [$2$], [$1.5$],
    [$4$], [$1,3$], [$2$], [$2$],
    [$5$], [$1,2,3,4$], [$4$], [$1.25$],
    [$6$], [$1,5$], [2], [$3$],
    [$7$], [$1,2,3,4,5,6$], [$6$], [$1.1666 dots.c$],
    [$8$], [$1,3,5,7$], [$4$], [$2$],
    [$9$], [$1,2,4,5,7,8$], [$6$], [$1.5$],
    [$10$], [$1,3,7,9$], [$4$], [$2.5$],
  )
  #v(0.5em)
]

We can see that $n\/phi(n)$ is maximum for $n=6$.

*Find the value of $n < 1 thin 000 thin 000$ for which $n\/phi(n)$ is maximum.*

_(Inspired by problem 69 of Project Euler)_
]


#problem-block(number: 70, title: [Circular permutation], level: 1)[
Take the number $102564$. By moving the last digit completely to the left, we obtain a multiple (different from the original number).

Indeed, $4 times 102564 = 410256$.

*Add all $6$-digit numbers that have this property.*

_(Proposed by Le Coyote)_
]


#problem-block(number: 71, title: [$567^2 = 321489$], bm-title: [567² = 321489], level: 1)[
$567^2 = 321489$

This equation uses all the numbers from $1$ to $9$, once each (except for the square).

*What is the only other number that, when squared, has the same property?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 72, title: [...xxx], level: 1)[
Of all integers less than $1$ billion, how many are squares ending with exactly $3$ identical digits?

For example, $213444 = 462^2$.

_(Proposed by Le Coyote)_
]


#problem-block(number: 73, title: [Palindromes and palindrome squares], level: 1)[
An integer is a palindrome when it reads the same backward as forward. For example, $235532$ and $636$ are palindromes.

*What is the largest $7$-digit palindrome whose square is also a palindrome?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 74, title: [Chain of factorial sums], level: 3)[
The number $145$ is well known for the property that the sum of the factorial of its digits equals $145$:
$ 1! + 4! + 5! = 1 + 24 + 120 = 145 $

Using this process, $169$ produces the longest loop of numbers. It turns out that there are only three such loops:
$
&169 -> 363601 -> 1454 -> 169\
&871 -> 45361 -> 871\
&872 -> 45362 -> 872
$

It is not difficult to prove that any starting number will eventually produce a loop. For example,
$
&69 -> 363600 -> 1454 -> 169 -> 363601 (-> 1454)\
&78 -> 45360 -> 871 -> 45361 (-> 871)\
&540 -> 145 (-> 145)
$

$69$ produces a chain of $5$ different terms.

*What is the smallest number less than $5$ million that produces the longest chain of different terms?*

_(Inspired by problem 74 of Project Euler)_
]


#problem-block(number: 75, title: [A crazy conversation. Although...], level: 4)[
$X$ and $Y$ are two different integers greater than $1$, with $X+Y < 100$.\
Simon and Paul are two mathematicians. Simon knows the sum $S=X+Y$. Paul knows the product $P=X times Y$. Simon knows that Paul knows the product, and Paul knows that Simon knows the sum.\
A conversation ensues between the two mathematicians:

Paul says, "I can't find these numbers."\
Simon says, "I was sure you couldn't find them. I can't find them either."\
Paul says, "So, I found these numbers."\
Simon says, "If you could find them, then I found them too."

*What are these numbers? Give the answer as the product $X times Y times S times P$.*

_(Hans Freudenthal, "Nieuw Archief Voor Wiskunde", Series 3, Volume 17, 1969, page 152)_
]


#problem-block(number: 76, title: [Fishing], level: 2)[
The natural numbers are arranged as shown in the diagram below:

```
1st row:  1  2  6  7 15 16 ...
2nd row:  3  5  8 14 17 ...
3rd row:  4  9 13 18 ...
4th row: 10 12 ...
5th row: 11 ...
...    : ...
```

(Add as many rows as needed)

*In which row is the number 20142014 located?*

_(Inspired by the 2011 CMP problem from the mathematics and physics circle of the Société jurassienne d'émulation)_
]


#problem-block(number: 77, title: [Sum of two squares], level: 1)[
Two $4$-digit numbers have the following property: $a b c d = a b^2 + c d^2$.

$
1233 &= 12^2 + 33^2\
8833 &= 88^2 + 33^2
$

*What is the largest $8$-digit number of this type: $a b c d e f g h = a b c d^2 + e f g h^2$?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 78, title: [$a b c d = a^b times c^d$], bm-title: [abcd = a^b × c^d], level: 1)[
*What is the only number with the following pattern: $a b c d = a^b times c^d$?*

Note (May 1, 2014): This is not a cryptarithm. Two different letters can represent the same digit.

_(Henry Ernest Dudeney)_
]


#problem-block(number: 79, title: [A maximum product], level: 3)[
Take the first eight odd numbers $1$, $3$, $5$, $7$, $9$, $11$, $13$ and $15$, arranged in a certain order: $x_1$, $x_2$, $x_3$, $x_4$, $x_5$, $x_6$, $x_7$, $x_8$, such that the product
$ p = (2-x_1) dot (4-x_2) dot (6-x_3) dot (8-x_4) dot (10-x_5) dot (12-x_6) dot (14-x_7) dot (16-x_8) $
is as large as possible.

*What is the maximum product?*

_(Puzzle 68 from the book "70 énigmes corrigées pour lycéens et plus, tome 1", by Jacques Lévy)_
]


#problem-block(number: 80, title: [Consecutive years with the same number of divisors], level: 3)[

The year $2014$ has a special feature: it has the same number of divisors as the previous year ($2013$) and the following year ($2015$).

*How many years between $1$ and $3000$ (excluding these two years) have this feature?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 81, title: [Mirror squares], level: 2)[
Some square numbers have a curious property: their "mirror" is also a square. Furthermore, the square root of one of these two numbers is also the "mirror" of the square root of the other. For example:
$
&169 = 13^2 "and" 961 = 31^2\
&14884 = 122^2 "and" 48841 = 221^2
$

*What is the largest $9$-digit square number with this property?*

_(Puzzle 15 from the book "70 énigmes corrigées pour lycéens et plus, tome 1", by Jacques Lévy)_
]


#problem-block(number: 82, title: [Euler's indicator], level: 3)[
Two numbers are coprime if their greatest common divisor is $1$. For example, $8$ and $9$ are coprime.\
Euler's indicator is the function $phi$ that gives the number of strictly positive integers less than or equal to $n$ that are coprime with $n$.

- $phi(1) = 1$, by definition.
- $phi(2) = 1$, because $1$ is prime with all integers.
- $phi(3) = 2$, because $1$ and $2$ are prime with $3$.
- $phi(4) = 2$, because $1$ and $3$ are prime with $4$.
- $phi(5) = 4$, because $1$, $2$, $3$, and $4$ are prime with $5$.
- $phi(6) = 2$, because $1$ and $5$ are coprime with $6$.
- $phi(7) = 6$, because all numbers from $1$ to $6$ are coprime with $7$.
- $phi(8) = 4$, because among the numbers from $1$ to $8$, only the four numbers $1$, $3$, $5$, and $7$ are coprime with $8$.
- ...

*Find the smallest integer $n$ such that $phi(n) = phi(n+1) = phi(n+2)$.*

_(Proposed by Le Coyote)_
]


#problem-block(number: 83, title: [Pascal's Triangle], level: 3)[
To construct Pascal's triangle, place $1$ at the top of the pyramid, then $1$ and $1$ below it, on either side. The ends of the lines are always $1$, and the other numbers are the sum of the two numbers directly above them.

#align(center)[
  #v(0.5em)
  #image(width: 150pt, "../figures/triangle-pascal.gif")
  #v(0.5em)
]

*What is the smallest number greater than $1$ that appears $8$ times in Pascal's triangle?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 84, title: [A long journey], level: 2)[
I travel a distance as follows:

Step $1$: I move forward $1$ centimeter.\
Step $2$: I turn left $90 degree$ and move forward $2$ cm.\
Step $3$: I turn left $90 degree$ and move forward $3$ cm.\
...\
Step $N$: I turn left $90 degree$ and move forward $N$ centimeters.

At the end of a step, I find myself more than $65$ kilometers from my starting point (as the crow flies). Furthermore, this distance is a whole number of centimeters.

*What is the minimum length of the route (in centimeters)?*

_(Proposed by Jodyl, member of Défi Turing)_
]


#problem-block(number: 85, title: [Numbers with different digits], level: 1)[
There are $32 thin 490$ numbers with all different digits between $1$ and $100 thin 000$, for example, $4$, $72$, $1 thin 468$, $53 thin 920$, etc.

*What is the sum of these numbers?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 86, title: [The curious $2000$#super[th] term of a sequence], bm-title: [The curious 2000th term of a sequence], level: 2)[
We have a sequence whose first two terms are: $U_1 = 3\/2$ and $U_2 = 5\/3$.

We calculate the next term in the series using the formula $display(U_n = 2003-6002/U_(n-1)+4000/(U_(n-1)U_(n-2)))$.

*What will be the $2000$#super[th] term in the series?* Round to the nearest whole number.

P.S. No! $2000$ is not the correct answer...

_(Proposed by Jodyl, member of Défi Turing, based on an article by Jean-Michel Müller)_
]


#problem-block(number: 87, title: [The chaotic fate of role-players], level: 3)[
One million players participate in a game that has $10$ levels. At the beginning, all players are at level $1$.

At the end of each round of play, each player rolls a balanced twelve-sided die, numbered from $1$ to $12$. The player advances one level if they roll a number higher than their current level. Otherwise, they remain at the same level.

Be careful! At level $10$, "advancing one level" means returning to level $1$!

After a certain amount of time, the number of players at each level tends to stabilize.

*What will be the average number of players at level $10$?* We will round to the nearest whole number.

_(Proposed by Jodyl, member of Défi Turing)_
]


#problem-block(number: 88, title: [Friday the 13th], level: 2)[
2014 was a year with few Friday the 13ths, with only one in June.

*Between January 1#super[st] 2001 and December 31#super[th] 2100, how many Friday the 13ths were there?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 89, title: [Square cryptarithm], level: 2)[
$A B C D C B A$ is a $7$-digit number encoded using the $4$ letters $A$, $B$, $C$ and $D$. Each letter always represents the same digit, and two different letters always represent two different digits.

*Give the largest square of the form $A B C D C B A$.*

_(FFJM - Swiss Final 2014, problem 18)_
]


#problem-block(number: 90, title: [Light!], level: 1)[
$276$ lamps are numbered from $1$ to $276$.\
To pass the time, $25$ children take turns pressing the switches. The first child presses every switch. The second presses switches $2$, $4$, $6$, etc. (all switches with a number that is a multiple of $2$), the third presses switches $3$, $6$, $9$, etc. The fourth presses all switches with a number that is a multiple of $4$, and so on until the $25$th child.\
Before the first child presses the buttons, all the lights are off.

*How many lights will be on after all $25$ children have pressed the buttons?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 91, title: [An almost true conjecture], level: 2)[
A conjecture states that all odd numbers can be written in the form $p + 2 times k^2$, where $p$ is a prime number and $k$ is a positive integer or zero.

$
9 &= 7 + 2 times 1^2\
15 &= 7 + 2 times 2^2\
21 &= 3 + 2 times 3^2\
25 &= 7 + 2 times 3^2\
27 &= 19 + 2 times 2^2\
33 &= 31 + 2 times 1^2
$

However, this conjecture is false.

*Give the sum of the numbers between $2$ and $100 thin 000$ that contradict this conjecture.*

_(A conjecture by Goldbach from 1752, disproved by M. A. Stern and his students in 1856.)_
]


#problem-block(number: 92, title: [Sum of consecutive integers equals $2014$], bm-title: [Sum of consecutive integers equals 2014], level: 2)[
The number $2014$ can be written as a sum of consecutive positive integers.

For example: $502 + 503 + 504 + 505 = 2014$.

There are other possibilities.

*Give the product of the first terms of all possible sums (including the example).*

_(FFJM - Swiss Final 2014, problem 16)_
]


#problem-block(number: 93, title: [Sums of prime numbers], level: 4)[
It is possible to write $10$ as a sum of prime numbers in exactly five ways:
$
&7 + 3\
&5 + 5\
&5 + 3 + 2\
&3 + 3 + 2 + 2\
&2 + 2 + 2 + 2 + 2
$

*What is the smallest integer that can be written as a sum of prime numbers in more than one million different ways?*

_(Problem 77 of Project Euler)_
]


#problem-block(number: 94, title: [$1$ or $89$?], bm-title: [1 or 89?], level: 3)[
A sequence of integers is created as follows: the next number in the list is obtained by adding the squares of the digits of the previous number.

Two examples:
$
&44 -> 32 (=16+16) -> 13 (=9+4) -> 10 (=1+9) -> bold(1) -> bold(1)\
&85 -> bold(89) -> 145 -> 42 -> 20 -> 4 -> 16 -> 37 -> 58 -> bold(89)
$

We can see that a sequence that reaches $1$ or $89$ will remain stuck in an infinite loop. The most incredible thing is that with any strictly positive starting number, any sequence will eventually reach $1$ or $89$.

*How many starting numbers less than or equal to $5$ million will reach $89$?*

_(Problem 92 of Project Euler)_
]


#problem-block(number: 95, title: [Counting rectangles], level: 3)[
In a $3 times 2$ rectangular grid, there are $18$ rectangles (squares are also counted as rectangles):

#align(center)[
  #v(0.5em)
  #image(width: 200pt, "../figures/095.gif")
  #v(0.5em)
]

*Find the area of the grid with the number of rectangles closest to $5$ million.*

_(Problem 85 of Project Euler)_
]


#problem-block(number: 96, title: [$p^2 + q^3 + r^4$], bm-title: [p^2 + q^3 + r^4], level: 3)[
$28$ is the smallest number that can be written as $p^2 + q^3 + r^4$, where $p$, $q$ and $r$ are prime numbers.

$
28 &= 2^2 + 2^3 + 2^4\
33 &= 3^2 + 2^3 + 2^4\
49 &= 5^2 + 2^3 + 2^4\
47 &= 2^2 + 3^3 + 2^4
$

*How many numbers less than or equal to $1$ billion can be written in this way?*

_(Problem 87 of Project Euler)_
]


#problem-block(number: 97, title: [Even/odd cryptarithm], level: 3)[
A cryptarithm is a numerical and logical puzzle consisting of a mathematical equation in which letters represent numbers to be found.\
In the multiplication below, `I` stands for an odd number and `P` for an even number. For example, `PPII` could be the number $4413$ or $2873$.

#align(center)[
```
    I P P
x     P P
---------
  P I P P
  P I P
---------
  I I P P
```
]

*What is the value of this product (`IIPP`)?*

_(Problem 56 from "100 jeux de chiffres", by Pierre Berloquin)_
]


#problem-block(number: 98, title: [Right triangles with integer coordinates], level: 3)[
The points $P(x_1, y_1)$ and $Q(x_2, y_2)$ have integer coordinates and form a triangle $O P Q$ with the origin. There are exactly $14$ right-angled triangles $O P Q$ for $0 <= x_1, y_1, x_2, y_2 <= 2$.

#align(center)[
  #v(0.5em)
  #grid(
    align: horizon,
    columns: (auto,)*2,
    column-gutter: 10pt,
    image(width: 100pt, "../figures/098_1.gif"),
    image(width: 225pt, "../figures/098_2.gif")
  )
  #v(0.5em)
]

*How many right-angled triangles $O P Q$ are there for $0 <= x_1, y_1, x_2, y_2 <= 60$?*

_(Problem 91 of Project Euler)_
]


#problem-block(number: 99, title: [The lucky year], level: 2)[
The terms $1$, $2$, $3$ and $4$ of a sequence are $13^0$, $13^1$, $13^2$ and $2014$, respectively. Each subsequent term in the sequence is always equal to the sum of the previous four terms.\
The $5$th term of the sequence is therefore equal to $1 + 13 + 169 + 2014 = 2197$.

*How many digits does the $2014$th term of the sequence have?*

_(Problem 18 from the semifinals of the 2014 Mathematical and Logical Games)_
]


#problem-block(number: 100, title: [Magic square], level: 3)[
Complete the magic square below using only prime numbers between $2$ and $100$.
#footnote[The sums of the three numbers in each row, each column, and both main diagonals are the same.]

#let b = table.cell(fill: aqua)[]

#align(center)[
  #v(0.5em)
  #table(
    align: center,
    columns: (18pt,)*3,
    stroke: black + 0.75pt,
    b, [], [$7$],
    [$1$], b, [],
    b, [$13$], []
  )
  #v(0.5em)
]

*Give the product of the $3$ blue squares as your answer.*

_(Problem 70 from "100 jeux de chiffres", by Pierre Berloquin)_
]


#problem-block(number: 101, title: [Division by 11], level: 2)[
Mathilde has just divided a number $n$ by $11$. The quotient, which is exact, is equal to the sum of the cubes of the digits of $n$.

For example: $6171\/11 = 561 = 6^3 + 1^3 + 7^3 + 1^3$.

*Give the sum of the numbers $n$ that have this property.*

_(Inspired by problem 15 from the semifinals of the 2014 International Mathematical and Logic Games Championship)_
]


#problem-block(number: 102, title: [$1741725 = 1^7 + 7^7 + 4^7 + 1^7 + 7^7 + 2^7 + 5^7$], bm-title: [1741725 = 1^7 + 7^7 + 4^7 + 1^7 + 7^7 + 2^7 + 5^7], level: 2)[
The number $1741725$ is the smallest $7$-digit number such that $1741725 = 1^7 + 7^7 + 4^7 + 1^7 + 7^7 + 2^7 + 5^7$.

*Give the sum of all $7$-digit numbers that have this property.*

_(Proposed by Le Coyote)_
]


#problem-block(number: 103, title: [Funny coordinates], level: 2)[
We place the integers in a table according to the layout below:

#align(center)[
  #v(0.5em)
  #image(width: 200pt, "../figures/103.gif")
  #v(0.5em)
]

- A row is designated by the number furthest to the left in that row.
- A column is designated by the topmost number in that column.
- The position of a number is identified by these two coordinates. For example, $15$ is in position $(10,9)$.

*What are the coordinates of $2014$ in this table?* Give the product of the two coordinates as your answer.

_(Problem from the magazine Logimath)_
]


#problem-block(number: 104, title: [Sequence of integers with the same number of divisors], level: 3)[
The number $242$ is the beginning of a sequence of four consecutive integers with the same number of divisors. Indeed, $242$, $243$, $244$ and $245$ each have $6$ divisors:
$
242&: 1, 2, 11, 22, 121, 242\
243&: 1, 3, 9, 27, 81, 243\
244&: 1, 2, 4, 61, 122, 244\
245&: 1, 5, 7, 35, 49, 245\
$

Consider integers less than $50 thin 000$.\
*What is the smallest integer that is the beginning of the longest sequence of integers with the same number of divisors?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 105, title: [Arithmetic expressions], level: 4)[
Let us calculate integers using exactly one of each digit from the set ${1, 2, 3, 4}$, with the four arithmetic operations $+$, $-$, $times$, $\/$ and parentheses.

For example,
$
8 &= (4 times (1 + 3)) \/ 2\
14 &= 4 times (3 + 1 \/ 2)\
19 &= 4 times (2 + 3) - 1\
36 &= 3 times 4 times (2 + 1)
$

Concatenating digits, such as $12 + 34$, is not allowed.

Using the set ${1, 2, 3, 4}$, it is possible to obtain $31$ different numbers, with a maximum of $36$; all numbers from $1$ to $28$ can be obtained.

*Find the set of $4$ distinct digits $a < b < c < d$, for which the longest string of consecutive integers from $1$ to $n$ can be obtained.* Give the string $a b c d$ as the answer.

_(Problem 93 of Project Euler)_
]


#problem-block(number: 106, title: [Two cryptarithms], level: 3)[
A cryptarithm is a numerical and logical puzzle consisting of a mathematical equation in which letters represent numbers to be found.

We know that `XYZ + AB = CDEF` and that `XYZ - AB = BGA`.

*What is the value of the product `XYZ` $times$ `AB`?*

_(Problem 49 from "100 jeux de chiffres", by Pierre Berloquin)_
]


#problem-block(number: 107, title: [Pandigital square], level: 1)[
We say that an integer is pandigital if it is composed of all the digits from $0$ to $9$. For example, $1023456789$ is the smallest pandigital integer.

*What is the smallest pandigital square?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 108, title: [Happy palindrome year!], level: 3)[
$2015$ is a palindrome number... in base $2$. Indeed, $2015 = 11111011111_2$.

This is not that rare, since $2016$ is also a palindrome number in base $2$ and even in base $3$ (provided you add zeros to the left). In fact, $2016 = 0000011111100000_2 = 002202200_3$.

*If we consider bases from $2$ to $16$, how many years of the 3rd millennium ($2001$--$3000$) will be palindromic numbers in at least one of these bases?* If necessary, add zeros to the left, regardless of the base. For example, $2020$ will be considered a palindrome, because it could be written as $02020_10$.

_(Proposed by Le Coyote)_
]


#problem-block(number: 109, title: [Feline cryptarithm], level: 1)[
A cryptarithm is a numerical and logical puzzle consisting of a mathematical equation in which letters represent numbers to be found.

#align(center)[`CHAT + CHAT = MINOU`]

*Let $x$ be the smallest possible value of `MINOU` and $y$ the largest. What is the value of $x + y$?*

_(Problem 75 from "100 jeux de chiffres", by Pierre Berloquin)_
]


#problem-block(number: 110, title: [Probability: $50%$], bm-title: [Probability: 50%], level: 4)[
Two balls are drawn at random from an urn containing blue and red balls.\
If the urn contains $21$ colored balls, 15 blue and 6 red, the probability of drawing $2$ blue balls is $P("BB") = (15\/21)times(14\/20) = 1\/2$.\
The next blue/red distribution that gives $P("BB") = 1\/2$ is $85$ blue and $35$ red: $P("BB") = (85\/120)times(84\/119) = 1\/2$.

*Find the first blue/red distribution where $P("BB") = 1\/2$, in an urn containing more than $10$ billion balls.* Give the number of blue balls as your answer.

_(Problem 100 of Project Euler)_
]


#problem-block(number: 111, title: [The Baron's Number], level: 1)[
*What is the only number $n > 1$ such that*
$ n = d_k^(d_k) + d_(k-1)^(d_(k-1)) + dots.c + d_2^(d_2) + d_1^(d_1) $

The $d_i$ are the digits that make up the number $n$.\
By convention, $0^0 = 1$.

_(#link("https://fr.wikipedia.org/wiki/Nombre_de_M%C3%BCnchhausen")[Wikipédia: Nombre de Münchhausen])_
]


#problem-block(number: 112, title: [Harmony], level: 3)[
Fill in the boxes in the grid below with whole numbers, so that each of these ten newly filled boxes contains a number that is the average of the numbers contained in the four boxes with which it shares a side.

#align(center)[
  #v(0.5em)
  #image(width: 150pt, "../figures/112.gif")
  #v(0.5em)
]

*What is the product of the numbers in these $10$ newly filled boxes (excluding any $0$s)?*

_(Jeux & Stratégie No. 13, February 1982, p.60. Proposed by Over_score, member of  Défi Turing)_
]


#problem-block(number: 113, title: [Triangular and tetrahedral numbers], level: 2)[
A triangular number is a figurative number that can be represented by a triangle. The first triangular numbers are: $1$, $3$, $6$, $10$, $15$, $21$, $28$, $36$, $45$, $55$, ...\
A tetrahedral number is a figurative number that can be represented by a pyramid with a triangular base, i.e., a tetrahedron. The first tetrahedral numbers are: $1$, $4$, $10$, $20$, $35$, $56$, $84$, $120$, $165$, $220$, ...

#align(center)[
  #v(0.5em)
  #grid(
    align: horizon,
    columns: (auto,)*2,
    column-gutter: 10pt,
    image(width: 240pt, "../figures/113a.png"),
    image(width: 150pt, "../figures/113b.png"),
    [The first six triangular numbers],
    [The fifth tetrahedral number ($35$)]
  )
  #v(0.5em)
]

We can see that the numbers $1$ and $10$ are both triangular and tetrahedral.

*What is the largest number that is both triangular and tetrahedral?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 114, title: [$49$th natural Kaprekar number], bm-title: [49th natural Kaprekar number],  level: 2)[
A natural integer $k$ with $n$ digits is called a natural Kaprekar number if its square can be broken down into a right part with $n$ digits and a left part with $n$ or $n-1$ digits such that their sum is $k$.

$45$ is the $3$rd natural Kaprekar number, because $45^2 = 2025$ and $20 + 25 = 45$.\
$297$ is the $6$th natural Kaprekar number, because $297^2 = 88209$ and $88+209 = 297$.

The first $15$ natural Kaprekar numbers are: $1$, $9$, $45$, $55$, $99$, $297$, $703$, $999$, $2223$, $2728$, $4950$, $5050$, $7272$, $7777$, $9999$.

*What is the $49$th natural Kaprekar number?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 115, title: [Just four digits], level: 3)[
Only two digits ($0$ and $1$) are needed to write a correct multiplication corresponding to the configuration below.

#align(center)[
  #v(0.5em)
  #image(width: 100pt, "../figures/115a.gif")
  #v(0.5em)
]

There are other solutions, such as $1111 times 11$, for example, which use only $1$s and $2$s.

With the configuration below, this is no longer possible. Even three digits are not enough. With four digits, it is finally possible. There are only two multiplications that satisfy this condition.

#align(center)[
  #v(0.5em)
  #image(width: 100pt, "../figures/115b.gif")
  #v(0.5em)
]

*What is the product of the results of these two multiplications?*

_(Jeux & Stratégie No. 13, February 1982, p.56. Proposed by Over_score, member of  Défi Turing)_
]


#problem-block(number: 116, title: [Quadruplet of integers divisible by a cube], level: 3)[
$1375$, $1376$ and $1377$ form the smallest triplet of consecutive integers that are all divisible by a cube other than $1$. Indeed, $1375$ is divisible by $125$, $1376$ by $8$, and $1377$ by $27$.

*What is the smallest quadruplet with this property?* Give the smallest of the $4$ numbers as your answer.

_(Proposed by Le Coyote)_
]


#problem-block(number: 117, title: [Almost prime numbers], level: 3)[
A positive integer $n$ is said to be "almost prime" if there are two distinct prime numbers $p$ and $q$ such that $n = p q$. Remember that $1$ is not prime.

*How many almost prime numbers smaller than $100 thin 000$ are there?*

_(Problem from July 25th of the "Calendrier mathématique 2014")_
]


#problem-block(number: 118, title: [Sequence of multiples], level: 3)[
Let us consider the ten numbers: $1$, $2$, $3$, $4$, $5$, $6$, $8$, $9$, $10$, $12$.\
We want to order them so that, for any two consecutive numbers, one is always a multiple of the other.

For example: $6$, $3$, $9$, $1$, $5$, $10$, $2$, $8$, $4$, $12$.

*How many orders satisfy this condition?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 119, title: [Number of divisors], level: 3)[
The number $80$ has $10$ divisors: $1$, $2$, $4$, $5$, $8$, $10$, $16$, $20$, $40$ and $80$.

*Given that $50! = 50 times 49 times 48 times 47 times dots.c times 3 times 2 times 1$, give the number of divisors of $50!.$*

_(Proposed by Le Coyote)_
]


#problem-block(number: 120, title: [The origin is in a triangle... or not], level: 3)[
Three distinct points are placed randomly on the Cartesian plane, with $-1000 <= x, y <= 1000$, such that a triangle is formed.\
Consider the following triangles $A B C$ and $D E F$:
$
A(-340, 495), B(-153, -910), C(835, -947)\
D(-175, 41), E(-421, -714), F(574, -645)
$

We can verify that the origin $(0, 0)$ is inside triangle $A B C$, but outside triangle $D E F$.

The file *120-fichier.txt*#footnote([This text file _120-fichier.txt_ is also attached to this PDF.]) (right click and "Save link as...") contains the coordinates of the vertices of ten thousand triangles.

*How many of these triangles contain the origin?*

*Note:* the first two lines of the file represent the triangles in the example given above.

_(Problem 102 of Project Euler)_
]


#problem-block(number: 121, title: [How many magic squares?], level: 2)[
To create a magic square, fill in the nine boxes in the square below with the numbers $1$ to $9$ so that the sum of the numbers in each four-box square is always the same.

*Example:*

#align(center)[
  #v(0.5em)
  #table(
    align: center,
    columns: (18pt,)*3,
    stroke: black + 0.75pt,
    [9], [1], [8],
    [2], [7], [3],
    [6], [4], [5]
  )
  #v(0.5em)
]

$9+1+2+7 = 1+8+7+3 = 2+7+6+4 = 7+3+4+5 = 19$.

*How many magic squares are there (ignoring symmetries)?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 122, title: [How many heterogeneous squares?], level: 2)[
To obtain a heterogeneous square of order $3$, fill in the nine boxes of the square below with the numbers $1$ to $9$ so that the eight sums of the three numbers in the rows, columns, and two diagonals are all different.

*Example:*

#align(center)[
  #v(0.5em)
  #table(
    align: center,
    columns: (18pt,)*3,
    stroke: black + 0.75pt,
    [4], [5], [7],
    [1], [3], [8],
    [9], [2], [6]
  )
  #v(0.5em)
]

$4+5+7 != 1+3+8 != 9+2+6 != 4+1+9 != 5+3+2 != 7+8+6 != 4+3+6 != 7+3+9$.

*How many heterogeneous squares of order $3$ are there (not counting symmetries)?*

_(Based on problem 15 in the book "Le jardin du Sphinx" by Pierre Berloquin)_
]


#problem-block(number: 123, title: [Antimagic squares], level: 3)[
In an antimagic square, the sums of the rows, columns, and diagonals must not only all be different, as in a heterogeneous square (see problem $122$). The sums must also be consecutive, for example from $29$ to $38$.\
There are no antimagic squares of order $1$, $2$ or $3$.

*How many antimagic squares are there that complete the partially filled square below?*

#align(center)[
  #v(0.5em)
  #table(
    align: center,
    columns: (18pt,)*4,
    stroke: black + 0.75pt,
    [#hide($0$)], [], [], [],
    [#hide($0$)], [], [], [],
    [], [], [14], [13],
    [16], [15], [4], [2]
  )
  #v(0.5em)
]

_(Based on problem 16 in the book "Le jardin du Sphinx" by Pierre Berloquin)_
]


#problem-block(number: 124, title: [Prime numbers everywhere!], level: 2)[
$1373$ is an interesting prime number because if you look at all the substrings of at least two consecutive digits that make it up, you only see prime numbers.

Indeed, $13$, $37$, $73$, $137$, $373$ and $1373$ are prime numbers.

*What is the largest prime number less than 10 million that has this property?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 125, title: [Wrapping a parallelepiped], level: 4)[
The minimum number of cubes needed to cover all visible faces of a rectangular parallelepiped measuring $3 times 2 times 1$ is $22$.

#align(center)[
  #v(0.5em)
  #image(width: 240pt, "../figures/125.gif")
  #v(0.5em)
]

If we then added a second layer to this solid, it would take $46$ cubes to cover all visible faces, the third layer would require $78$ cubes, and the fourth layer would require $118$ cubes.\
However, the first layer on a parallelepiped measuring $5 times 1 times 1$ also requires $22$ cubes. Similarly, the first layer on parallelepipeds with dimensions $5 times 3 times 1$, $7 times 2 times 1$ and $11 times 1 times 1$ all require $46$ cubes.\
We will use the notation $C(n)$ to represent the number of rectangular parallelepipeds that contain $n$ cubes in one of their layers. So, $C(22) = 2$, $C(46) = 4$, $C(78) = 5$, and $C(118) = 8$.\
It turns out that $154$ is the smallest value of $n$ for which $C(n) = 10$.

*Find the smallest value of n for which $C(n) = 100$.*

_(Problem 126 of Project Euler)_
]


#problem-block(number: 126, title: [Subtriples], level: 1)[
Pierre de Fermat (1601?--1665) used the term "subdouble" to refer to an integer whose sum of proper divisors is equal to twice that number.

For example, the sum of the proper divisors of $120$ is equal to:\
$1 + 2 + 3 + 4 + 5 + 6 + 8 + 10 + 12 + 15 + 20 + 24 + 30 + 40 + 60 = 240$.

Similarly, he uses the term "subtriple" to refer to an integer whose sum of proper divisors is equal to three times that number.

*Give the sum of the subtriples less than 100 thin 000.*

_(Proposed by Le Coyote)_
]


#problem-block(number: 127, title: [Perpetual calendar], level: 2)[
A perpetual calendar consists of $14$ different calendars. This is because January 1#super[st] is one of seven days of the week, and a year may or may not be a leap year. So $7 times 2 = 14$.\
You will start your calendar collection in $2016$. When the calendar for a given year is identical to one you already have, you will not buy it.

*When you have completed your collection, what will be the sum of the years on your $14$ calendars?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 128, title: [The pentacle], level: 2)[
We want to fill the ten discs in the figure below with different integers between $1$ and $12$, so that the five rows of four numbers and the circle of five numbers have the same sum.

#align(center)[
  #v(0.5em)
  #image(width: 150pt, "../figures/128.gif")
  #v(0.5em)
]

*Give the number formed by placing the four numbers on the blue circles side by side, read from left to right.*

_(Problem from the Euromath Cup)_
]


#problem-block(number: 129, title: [More than 4...], level: 3)[
Let $F(n)=1+2+3+dots.c+n$ be the sum of the first n non-zero integers.\
Before adding them up, I wanted to write all the integers from $1$ to $n$ on my computer. The only problem was that the "$4$" key on my keyboard wasn't working.
So I had the idea of replacing all the "$4$"s with other values, for example with "$3$"s.\
By doing so, it is clear that the sum obtained will be less than $F(n)$.\
To correct this slightly, I decided to replace the "$4$" alternately with a "$3$" and then with a "$5$", and I noted $S(n)$ as the sum of the $n$ numbers obtained.

For example, we have $S(6)=1+2+3+3+5+6=20$ and $F(6)=21$.\
Similarly, $S(20)=1+2+3+3+5+dots.c+12+13+15+15+16+dots.c+20=F(20)$.\
We also have $S(50)=1256$ and $F(50)=1275$.

*What is the largest value of $n$, less than one million, for which we have $S(n)=F(n)$?*

_(Proposed by Olivier Rochoir)_
]


#problem-block(number: 130, title: [Optimal horizontal line], level: 3)[
The file *130-fichier.txt*#footnote([This text file _130-fichier.txt_ is also attached to this PDF.]) contains the coordinates of $1000$ points in the plane.

*What is the height of the horizontal line that minimizes the sum of the distances to the points?* If there are several lines, give the average of the heights.

_(Proposed by Le Coyote)_
]

