#import "../templates/preamble.typ": *


#problem-block(number: 1, title: [Sum of Multiples of 5 or 7])[
If we list all the natural numbers less than $20$ that are multiples of $5$ or $7$, we get $5$, $7$, $10$, $14$ and $15$. The sum of these numbers is $51$.

*Find the sum of all multiples of $5$ or $7$ less than $2013$.*

_(Inspired by problem 1 of Project Euler)_
]


#problem-block(number: 2, title: [Sum of Odd-valued Terms in Fibonacci Sequence])[
Each new term in the Fibonacci sequence is generated by adding the two preceding terms. Starting with $1$ and $1$, the first $10$ terms are as follows:
$ 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, dots $

*By considering the terms in the Fibonacci sequence whose values do not exceed $4$ million, find the sum of the odd-valued terms.*

_(Inspired by problem 2 of Project Euler)_
]


#problem-block(number: 3, title: [Largest Prime Factor of Composite Number])[
The prime factors of the number $2013$ are $3$, $11$ and $61$, because $3 times 11 times 61 = 2013$.

*What is the largest prime factor of the number $20130101$?*

_(Inspired by problem 3 of Project Euler)_
]


#problem-block(number: 4, title: [Largest Palindrome of Multiplying Two Numbers])[
A palindromic number reads the same from left to right and from right to left.\
The largest palindrome that can be obtained by multiplying two 2-digit numbers is $9009 = 99 times 91$.

*What is the largest palindrome that can be obtained by multiplying a 4-digit number by a 3-digit number?*

_(Inspired by problem 4 of Project Euler)_
]


#problem-block(number: 5, title: [Sum of Digits of $2^2222$], bm-title: [Sum of Digits of 2^2222])[
$2^15 = 32768$ and the sum of its digits is $3 + 2 + 7 + 6 + 8 = 26$.

*What is the sum of the digits that make up the number $2^2222$?*

_(Inspired by problem 16 of Project Euler)_
]


#problem-block(number: 6, title: [Sum of Digits in Number $2013!$], bm-title: [Sum of Digits in Number 2013!])[
$n!$ means $n times (n-1) times dots.c times 3 times 2 times 1$.\
For example, $10! = 10 times 9 times dots.c times 3 times 2 times 1 = 3628800$.\
The sum of the digits in the number $10!$ is $3 + 6 + 2 + 8 + 8 + 0 + 0 = 27$.

*Find the sum of the digits in the number $2013!$.*

_(Inspired by problem 20 of Project Euler)_
]


#problem-block(number: 7, title: [What is the $23456$#super[th] Prime Number?], bm-title: [What is the 23456th Prime Number?])[
By listing the first six prime numbers: $2$, $3$, $5$, $7$, $11$ and $13$, we see that the $6$#super[th] prime number is $13$.

*What is the $23456$#super[th] prime number?*

_(Inspired by problem 7 of Project Euler)_
]


#problem-block(number: 8, title: [Rectangle-$6400$], bm-title: [Rectangle-6400])[
In a rectangle with a length of $4$ and a width of $3$, we can draw $12$ squares with a side length of $1$, $6$ squares with a side length of $2$, and $2$ squares with a side length of $3$. In total, we can draw $20$ squares. We will call this a rectangle-$20$.

*What is the area of ​​the rectangle-$6400$ whose shape is closest to a square?*

Note: The dimensions are whole numbers for both the rectangle and the squares.

_(Inspired by the 2012 CMP problem from the mathematics and physics circle of the Société jurassienne d'émulation)_
]


#problem-block(number: 9, title: [Pythagorean Triplet])[
A triplet of non-zero natural numbers $(a, b, c)$ is Pythagorean if $a^2 + b^2 = c^2$. For example, $(3, 4, 5)$ is a Pythagorean triplet.

*Among the Pythagorean triples $(a, b, c)$ such that $a + b + c = 3600$, give the largest product $a times b times c$.*

_(Inspired by problem 9 of Project Euler)_
]


#problem-block(number: 10, title: [Sum of Prime Numbers])[
The sum of the prime numbers between $1$ and $10$ is $2 + 3 + 5 + 7 = 17$.

*Find the sum of the prime numbers between $1$ and $10 thin 000 thin 000$.*

_(Inspired by problem 10 of Project Euler)_
]


#problem-block(number: 11, title: [Mirror of Number])[
The "mirror image of a number $n$" is the number $n$ written from right to left. For example, $op("mirror")(7423) = 3247$.

*What is the largest number less than $10$ million that has the property: $op("mirror")(n) = 4 times n$?*

_(Proposed by Le Coyote)_
]


#problem-block(number: 12, title: [Triangular Numbers with Many Divisors])[
The sequence of triangular numbers is generated by adding the natural numbers. Thus, the $7$#super[th] triangular number is $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten triangular numbers are as follows:
$ 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, dots $

Let us list the divisors of the first seven triangular numbers:

$1 : 1$\
$3 : 1, 3$\
$6 : 1, 2, 3, 6$\
$10 : 1, 2, 5, 10$\
$15 : 1, 3, 5, 15$\
$21 : 1, 3, 7, 21$\
$28 : 1, 2, 4, 7, 14, 28$

We can see that $28$ is the first triangular number with more than five divisors.

*What is the value of the first triangular number with more than one thousand divisors?*

_(Inspired by problem 12 of Project Euler)_
]


#problem-block(number: 13, title: [Palindrome Square])[
The smallest palindromic square with an even number of digits is $698896 = 836^2$.

*What is the next palindromic square?*

_(Source: The Mathematical Gazette)_
]


#problem-block(number: 14, title: [Longest Syracuse Sequence])[
In mathematics, a "Syracuse sequence" is a sequence of natural numbers defined as follows:

We start with an integer greater than zero; if it is even, we divide it by $2$; if it is odd, we multiply it by $3$ and add $1$.\
By repeating the operation, we obtain a sequence of positive integers, each of which depends only on its predecessor.

There is a conjecture that says that the Syracuse sequence of any strictly positive integer reaches $1$.

For example, starting from 14, we construct the sequence of numbers: $14$, $7$, $22$, $11$, $34$, $17$, $52$, $26$, $13$, $40$, $20$, $10$, $5$, $16$, $8$, $4$, $2$, $1$. This is called the Syracuse sequence of the number $14$. Here, it has a length of $18$.

*For what starting number less than $1 thin 500 thin 000$ do we obtain the longest Syracuse sequence?* There are two solutions, give the smallest one.

_(Inspired by problem 14 of Project Euler)_
]


#problem-block(number: 15, title: [Numbers of Mage Hic])[
Fill in a $3 times 3$ grid with all the numbers from $1$ to $9$ (green squares). Then calculate the products of the three numbers in each row and each column (grey squares). Finally, add these six products together to obtain the blue number ($450$ in the example given).

#align(center)[
  #v(1em)
  #image("../figures/015.png")
  #v(1em)
]

*Of the $362 thin 880$ possible grids, what is the minimum blue number and the maximum blue number? Give the product of these two numbers as the result.*

_(Inspired by problem 12 from the 2013 FFJM Individual Quarter-Finals: "Le nombre du Mage Hic")_
]


#problem-block(number: 16, title: [THREE x NINE = TROIS x NEUF])[
A cryptarithm is a numerical and logical puzzle consisting of a mathematical equation in which letters represent numbers to be found. Each different letter represents a different number, and each number is represented by the same letter.

*Solve the cryptarithm below* (give the product obtained as the answer):

#align(center)[`THREE x NINE = TROIS x NEUF`]

*Constraints:*\
`THREE` and `NEUF` are multiples of $9$;\
`TROIS` and `NINE` are multiples of $3$.

_(Problem 18 from the quarter-finals of the 2003 Mathematical and Logical Games)_
]


#problem-block(number: 17, title: [Amicable numbers])[
Let $d(n)$ be the sum of the proper divisors of $n$ (divisors strictly smaller than $n$). If $d(a)=b$ and $d(b)=a$, with a different from $b$, then $a$ and $b$ are said to be amicable.\
For example, the proper divisors of $220$ are $1$, $2$, $4$, $5$, $10$, $11$, $20$, $22$, $44$, $55$ and $110$; therefore $d(220) = 284$. The proper divisors of $284$ are $1$, $2$, $4$, $71$ and $142$; therefore $d(284) = 220$. $220$ and $284$ are two amicable numbers.\
The sum of the amicable numbers between $1$ and $1000$ is $220 + 284 = 504$.

*What is the sum of the amicable numbers between $1$ and $100 thin 000$?*

_(Inspired by problem 21 of Project Euler)_
]


#problem-block(number: 18, title: [Sum of Non-Abundant Numbers])[
A perfect number is a number whose sum of proper divisors is exactly equal to the number itself. For example, the sum of the proper divisors of 28 would be $1 + 2 + 4 + 7 + 14 = 28$, which means that $28$ is a perfect number.

A number $n$ is called deficient if the sum of its proper divisors is less than $n$, and it is called abundant if this sum is greater than $n$.

Since $12$ is the smallest abundant number ($1 + 2 + 3 + 4 + 6 = 16$), the smallest number that can be written as the sum of two abundant numbers is $24$.

*Find the sum of all positive integers less than or equal to $2013$ that #underline[cannot] be written as the sum of two abundant numbers.*

_(Inspired by problem 23 of Project Euler)_
]


#problem-block(number: 19, title: [Close Encounters of the Fourth Kind])[
Little green men meet little blue men. To their great surprise, they notice that their hands do not have the same number of fingers: $7$ for the blue ones and $8$ for the green ones. But the scientists of both peoples notice that if you count on your fingers as shown in the figure, moving back and forth from the little finger to the thumb, then from the thumb to the little finger, certain numbers can be counted on both the ring finger of the blue hands and the ring finger of the green hands ($2$ and $14$, for example).\
These numbers have been termed "annular" by scholars.

#align(center)[
  #v(1em)
  #image(width: 300pt, "../figures/019.jpg")
  #v(1em)
]

*Calculate the sum of the ring numbers between $1$ and $2013$.*

_(Inspired by a problem from the Mathematical and Logical Games Championship)_
]


#problem-block(number: 20, title: [Hercules and the Hydra])[
A battle between Hercules and one (or more) hydra(s) can be described by the following steps:
- On the first blow, the Hydra loses a head, and a copy of the wounded Hydra (that is, one with one less head) appears. On the second blow, a Hydra loses a head, and two copies of the wounded Hydra appear. On the tenth blow, a Hydra loses a head, so ten copies appear, and so on.
- When a one-headed Hydra is struck, it disappears.
- To complicate matters, the treacherous Hera forces Hercules to cut off the heads in the worst possible order, so that it takes him as long as possible to destroy the Hydras.

#align(center)[
  #v(1em)
  #image(width: 240pt, "../figures/020.gif")
  Example: Hercules fights two two-headed hydras and two one-headed hydras.
  #v(1em)
]

*Assuming Hercules is capable of cutting off a head every second, how many seconds will it take him to defeat a four-headed hydra?*

_(Jean-Bernard Roux's problem)_
]
